// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: dynamodb
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn dynamodb_table_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "dynamodb.Table".into(),
            description: "Table resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "name".into(),
                            description: "Table name".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "billing_mode".into(),
                                description: "Billing mode".into(),
                                field_type: crate::provider::FieldType::String, /* Enum */
                                required: false,
                                default: Some(serde_json::json!("PAY_PER_REQUEST")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "partition_key".into(),
                                description: "Partition key attribute name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "partition_key_type".into(),
                                description: "Partition key type (S, N, B)".into(),
                                field_type: crate::provider::FieldType::String, /* Enum */
                                required: false,
                                default: Some(serde_json::json!("S")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "read_capacity".into(),
                                description: "Provisioned read capacity units".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(5)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "sort_key".into(),
                                description: "Sort key attribute name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "write_capacity".into(),
                                description: "Provisioned write capacity units".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(5)),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_dynamodb_table(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let name = config.require_str("/identity/name")?.to_string();

        let partition_key = config.require_str("/sizing/partition_key")?.to_string();
        let partition_key_type = config.str_or("/sizing/partition_key_type", "S");

        let mut key_schema = vec![
            aws_sdk_dynamodb::types::KeySchemaElement::builder()
                .attribute_name(&partition_key)
                .key_type(aws_sdk_dynamodb::types::KeyType::Hash)
                .build()
                .map_err(|e| {
                    ProviderError::InvalidConfig(format!("failed to build KeySchemaElement: {e}"))
                })?,
        ];

        let mut attr_defs = vec![
            aws_sdk_dynamodb::types::AttributeDefinition::builder()
                .attribute_name(&partition_key)
                .attribute_type(aws_sdk_dynamodb::types::ScalarAttributeType::from(
                    partition_key_type,
                ))
                .build()
                .map_err(|e| {
                    ProviderError::InvalidConfig(format!(
                        "failed to build AttributeDefinition: {e}"
                    ))
                })?,
        ];

        if let Some(sort_key) = config.optional_str("/sizing/sort_key") {
            let sort_key_type = config.str_or("/sizing/sort_key_type", "S");

            key_schema.push(
                aws_sdk_dynamodb::types::KeySchemaElement::builder()
                    .attribute_name(sort_key)
                    .key_type(aws_sdk_dynamodb::types::KeyType::Range)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!(
                            "failed to build KeySchemaElement: {e}"
                        ))
                    })?,
            );
            attr_defs.push(
                aws_sdk_dynamodb::types::AttributeDefinition::builder()
                    .attribute_name(sort_key)
                    .attribute_type(aws_sdk_dynamodb::types::ScalarAttributeType::from(
                        sort_key_type,
                    ))
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!(
                            "failed to build AttributeDefinition: {e}"
                        ))
                    })?,
            );
        }

        let billing_mode = config.str_or("/sizing/billing_mode", "PAY_PER_REQUEST");

        let mut req = self
            .dynamodb_client
            .create_table()
            .table_name(&name)
            .set_key_schema(Some(key_schema))
            .set_attribute_definitions(Some(attr_defs))
            .billing_mode(aws_sdk_dynamodb::types::BillingMode::from(billing_mode));

        if billing_mode == "PROVISIONED" {
            let rcu = config
                .pointer("/sizing/read_capacity")
                .and_then(|v| v.as_i64())
                .unwrap_or(5);
            let wcu = config
                .pointer("/sizing/write_capacity")
                .and_then(|v| v.as_i64())
                .unwrap_or(5);
            req = req.provisioned_throughput(
                aws_sdk_dynamodb::types::ProvisionedThroughput::builder()
                    .read_capacity_units(rcu)
                    .write_capacity_units(wcu)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!(
                            "failed to build ProvisionedThroughput: {e}"
                        ))
                    })?,
            );
        }

        let tags = super::extract_tags(config);
        for (k, v) in &tags {
            req = req.tags(
                aws_sdk_dynamodb::types::Tag::builder()
                    .key(k)
                    .value(v)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!("failed to build DynamoDB Tag: {e}"))
                    })?,
            );
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("CreateTable: {e}")))?;

        let table_name = result
            .table_description()
            .and_then(|t| t.table_name())
            .unwrap_or(&name);

        let provider_id = table_name;

        self.read_dynamodb_table(provider_id).await
    }

    pub(super) async fn read_dynamodb_table(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .dynamodb_client
            .describe_table()
            .table_name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DescribeTable: {e}")))?;

        let table = result
            .table()
            .ok_or_else(|| ProviderError::NotFound(format!("Table {provider_id}")))?;

        let billing = table
            .billing_mode_summary()
            .map(|b| {
                b.billing_mode()
                    .map(|m| m.as_str())
                    .unwrap_or("PAY_PER_REQUEST")
            })
            .unwrap_or("PAY_PER_REQUEST");

        // Extract key schema
        let key_schema = table.key_schema();
        let attr_defs = table.attribute_definitions();
        let partition_key = key_schema
            .iter()
            .find(|k| k.key_type() == &aws_sdk_dynamodb::types::KeyType::Hash)
            .map(|k| k.attribute_name())
            .unwrap_or("");
        let partition_key_type = attr_defs
            .iter()
            .find(|a| a.attribute_name() == partition_key)
            .map(|a| a.attribute_type().as_str())
            .unwrap_or("S");
        let sort_key = key_schema
            .iter()
            .find(|k| k.key_type() == &aws_sdk_dynamodb::types::KeyType::Range)
            .map(|k| k.attribute_name())
            .unwrap_or("");

        let mut sizing = serde_json::json!({
            "billing_mode": billing,
            "partition_key": partition_key,
            "partition_key_type": partition_key_type,
        });
        if !sort_key.is_empty() {
            let sort_key_type = attr_defs
                .iter()
                .find(|a| a.attribute_name() == sort_key)
                .map(|a| a.attribute_type().as_str())
                .unwrap_or("S");
            sizing["sort_key"] = serde_json::json!(sort_key);
            sizing["sort_key_type"] = serde_json::json!(sort_key_type);
        }

        let state = serde_json::json!({
            "identity": {
                "name": table.table_name().unwrap_or(""),
            },
            "sizing": sizing,
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "table_arn".into(),
            serde_json::json!(table.table_arn().unwrap_or("")),
        );
        outputs.insert(
            "table_name".into(),
            serde_json::json!(table.table_name().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: table.table_name().unwrap_or("").to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_dynamodb_table(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let billing_mode = config.str_or("/sizing/billing_mode", "PAY_PER_REQUEST");

        let mut req = self
            .dynamodb_client
            .update_table()
            .table_name(provider_id)
            .billing_mode(aws_sdk_dynamodb::types::BillingMode::from(billing_mode));

        if billing_mode == "PROVISIONED" {
            let rcu = config
                .pointer("/sizing/read_capacity")
                .and_then(|v| v.as_i64())
                .unwrap_or(5);
            let wcu = config
                .pointer("/sizing/write_capacity")
                .and_then(|v| v.as_i64())
                .unwrap_or(5);
            req = req.provisioned_throughput(
                aws_sdk_dynamodb::types::ProvisionedThroughput::builder()
                    .read_capacity_units(rcu)
                    .write_capacity_units(wcu)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!(
                            "failed to build ProvisionedThroughput: {e}"
                        ))
                    })?,
            );
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("UpdateTable: {e}")))?;

        self.read_dynamodb_table(provider_id).await
    }

    pub(super) async fn delete_dynamodb_table(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.dynamodb_client
            .delete_table()
            .table_name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_table: {e}")))?;
        Ok(())
    }
}
