// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: eks
// Resources: 2

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn eks_cluster_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "eks.Cluster".into(),
            description: "Cluster resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "name".into(),
                            description: "Cluster name".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "network".into(),
                        description: "Network configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "endpoint_private_access".into(),
                                description: "Enable private API endpoint".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: Some(serde_json::json!(false)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "endpoint_public_access".into(),
                                description: "Enable public API endpoint".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: Some(serde_json::json!(true)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "subnet_ids".into(),
                                description: "Subnet IDs for the cluster".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(
                                    crate::provider::FieldType::String,
                                )),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "role_arn".into(),
                                description: "IAM role ARN for the cluster".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "security_group_ids".into(),
                                description: "Additional security group IDs".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(
                                    crate::provider::FieldType::String,
                                )),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "version".into(),
                            description: "Kubernetes version (e.g. 1.28)".into(),
                            field_type: crate::provider::FieldType::String,
                            required: false,
                            default: None,
                            sensitive: false,
                        }],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_eks_cluster(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let endpoint_private_access = config.bool_or("/network/endpoint_private_access", false);
        let endpoint_public_access = config.bool_or("/network/endpoint_public_access", true);
        let name = config.require_str("/identity/name")?.to_string();
        let role_arn = config.require_str("/security/role_arn")?.to_string();
        let security_group_ids: Option<Vec<String>> = config
            .optional_array("/security/security_group_ids")
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            });
        let subnet_ids: Vec<String> = config
            .optional_array("/network/subnet_ids")
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();
        let version = config.optional_str("/sizing/version").map(String::from);

        let tags = super::extract_tags(config);

        let mut req = self
            .eks_client
            .create_cluster()
            .name(&name)
            .role_arn(&role_arn);

        if let Some(ref v) = version {
            req = req.version(v);
        }
        req = req.set_tags(Some(tags));
        let mut vpc_config_builder = aws_sdk_eks::types::VpcConfigRequest::builder();
        vpc_config_builder = vpc_config_builder.endpoint_private_access(endpoint_private_access);
        vpc_config_builder = vpc_config_builder.endpoint_public_access(endpoint_public_access);
        vpc_config_builder = vpc_config_builder.set_security_group_ids(security_group_ids);
        vpc_config_builder = vpc_config_builder.set_subnet_ids(Some(subnet_ids));
        let vpc_config = vpc_config_builder.build();
        req = req.resources_vpc_config(vpc_config);

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_cluster: {e}")))?;

        self.read_eks_cluster(&name).await
    }

    pub(super) async fn read_eks_cluster(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .eks_client
            .describe_cluster()
            .name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_cluster: {e}")))?;

        let resource = result
            .cluster()
            .ok_or_else(|| ProviderError::NotFound(format!("Cluster {provider_id}")))?;

        let state = serde_json::json!({
            "identity": {
                "name": provider_id,
            },
            "network": {
                "subnet_ids": resource.resources_vpc_config().map(|c| c.subnet_ids()).unwrap_or_default(),
            },
            "security": {
                "role_arn": resource.role_arn().unwrap_or(""),
                "security_group_ids": resource.resources_vpc_config().map(|c| c.security_group_ids()).unwrap_or_default(),
            },
            "sizing": {
                "version": resource.version().unwrap_or(""),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "cluster_arn".into(),
            serde_json::json!(resource.arn().unwrap_or("")),
        );
        outputs.insert("cluster_name".into(), serde_json::json!(provider_id));
        outputs.insert(
            "endpoint".into(),
            serde_json::json!(resource.endpoint().unwrap_or("")),
        );
        outputs.insert(
            "certificate_authority".into(),
            serde_json::json!(
                resource
                    .certificate_authority()
                    .and_then(|ca| ca.data())
                    .unwrap_or("")
            ),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_eks_cluster(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let version = config.optional_str("/sizing/version");

        let mut req = self.eks_client.update_cluster_version().name(provider_id);

        if let Some(v) = version {
            req = req.version(v);
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("update_cluster_version: {e}")))?;

        self.read_eks_cluster(provider_id).await
    }

    pub(super) async fn delete_eks_cluster(&self, provider_id: &str) -> Result<(), ProviderError> {
        self.eks_client
            .delete_cluster()
            .name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_cluster: {e}")))?;
        Ok(())
    }

    pub(super) fn eks_node_group_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "eks.NodeGroup".into(),
            description: "Nodegroup resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "name".into(),
                            description: "Node group name".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "network".into(),
                        description: "Network configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "cluster_name".into(),
                                description: "EKS cluster name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "subnet_ids".into(),
                                description: "Subnet IDs for node placement".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(
                                    crate::provider::FieldType::String,
                                )),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "node_role_arn".into(),
                            description: "IAM role ARN for node instances".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "desired_size".into(),
                                description: "Desired number of nodes".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(2)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "disk_size".into(),
                                description: "Node disk size in GiB".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(20)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "instance_types".into(),
                                description: "EC2 instance types for nodes".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(
                                    crate::provider::FieldType::String,
                                )),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "max_size".into(),
                                description: "Maximum number of nodes".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(3)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "min_size".into(),
                                description: "Minimum number of nodes".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(1)),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_eks_node_group(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let cluster_name = config.require_str("/network/cluster_name")?.to_string();
        let desired_size = config.i64_or("/sizing/desired_size", 2);
        let disk_size = config.i64_or("/sizing/disk_size", 20);
        let instance_types: Option<Vec<String>> =
            config.optional_array("/sizing/instance_types").map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            });
        let max_size = config.i64_or("/sizing/max_size", 3);
        let min_size = config.i64_or("/sizing/min_size", 1);
        let name = config.require_str("/identity/name")?.to_string();
        let node_role_arn = config.require_str("/security/node_role_arn")?.to_string();
        let subnet_ids: Vec<String> = config
            .optional_array("/network/subnet_ids")
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        let tags = super::extract_tags(config);

        let mut req = self
            .eks_client
            .create_nodegroup()
            .cluster_name(&cluster_name)
            .nodegroup_name(&name)
            .node_role(&node_role_arn);

        req = req.disk_size(disk_size as i32);
        if let Some(ref arr) = instance_types {
            for v in arr {
                req = req.instance_types(v);
            }
        }
        for v in &subnet_ids {
            req = req.subnets(v);
        }
        req = req.set_tags(Some(tags));
        let mut scaling_config_builder = aws_sdk_eks::types::NodegroupScalingConfig::builder();
        scaling_config_builder = scaling_config_builder.desired_size(desired_size as i32);
        scaling_config_builder = scaling_config_builder.max_size(max_size as i32);
        scaling_config_builder = scaling_config_builder.min_size(min_size as i32);
        let scaling_config = scaling_config_builder.build();
        req = req.scaling_config(scaling_config);

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_nodegroup: {e}")))?;

        let provider_id = format!("{}:{}", cluster_name, name);

        self.read_eks_node_group(&provider_id).await
    }

    pub(super) async fn read_eks_node_group(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let id_parts: Vec<&str> = provider_id.split(':').collect();
        if id_parts.len() != 2 {
            return Err(ProviderError::InvalidConfig(format!(
                "provider_id must be cluster_name:nodegroup_name, got: {provider_id}"
            )));
        }
        let cluster_name = id_parts[0];
        let nodegroup_name = id_parts[1];

        let result = self
            .eks_client
            .describe_nodegroup()
            .cluster_name(cluster_name)
            .nodegroup_name(nodegroup_name)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_nodegroup: {e}")))?;

        let resource = result
            .nodegroup()
            .ok_or_else(|| ProviderError::NotFound(format!("Nodegroup {provider_id}")))?;

        let state = serde_json::json!({
            "identity": {
                "name": provider_id,
            },
            "network": {
                "cluster_name": resource.cluster_name().unwrap_or(""),
                "subnet_ids": resource.subnets(),
            },
            "security": {
                "node_role_arn": resource.node_role().unwrap_or(""),
            },
            "sizing": {
                "desired_size": resource.scaling_config().and_then(|c| c.desired_size()).unwrap_or(0),
                "disk_size": resource.disk_size().unwrap_or(0),
                "max_size": resource.scaling_config().and_then(|c| c.max_size()).unwrap_or(0),
                "min_size": resource.scaling_config().and_then(|c| c.min_size()).unwrap_or(0),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "nodegroup_arn".into(),
            serde_json::json!(resource.nodegroup_arn().unwrap_or("")),
        );
        outputs.insert(
            "nodegroup_name".into(),
            serde_json::json!(resource.nodegroup_name().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_eks_node_group(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let id_parts: Vec<&str> = provider_id.split(':').collect();
        if id_parts.len() != 2 {
            return Err(ProviderError::InvalidConfig(format!(
                "provider_id must be cluster_name:nodegroup_name, got: {provider_id}"
            )));
        }
        let cluster_name = id_parts[0];
        let nodegroup_name = id_parts[1];

        let desired_size = config.optional_i64("/sizing/desired_size");
        let max_size = config.optional_i64("/sizing/max_size");
        let min_size = config.optional_i64("/sizing/min_size");

        let mut req = self
            .eks_client
            .update_nodegroup_config()
            .cluster_name(cluster_name)
            .nodegroup_name(nodegroup_name);

        let mut scaling_config_builder = aws_sdk_eks::types::NodegroupScalingConfig::builder();
        if let Some(v) = desired_size {
            scaling_config_builder = scaling_config_builder.desired_size(v as i32);
        }
        if let Some(v) = max_size {
            scaling_config_builder = scaling_config_builder.max_size(v as i32);
        }
        if let Some(v) = min_size {
            scaling_config_builder = scaling_config_builder.min_size(v as i32);
        }
        req = req.scaling_config(scaling_config_builder.build());

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("update_nodegroup_config: {e}")))?;

        self.read_eks_node_group(provider_id).await
    }

    pub(super) async fn delete_eks_node_group(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let id_parts: Vec<&str> = provider_id.split(':').collect();
        if id_parts.len() != 2 {
            return Err(ProviderError::InvalidConfig(format!(
                "provider_id must be cluster_name:nodegroup_name, got: {provider_id}"
            )));
        }
        let cluster_name = id_parts[0];
        let nodegroup_name = id_parts[1];

        self.eks_client
            .delete_nodegroup()
            .cluster_name(cluster_name)
            .nodegroup_name(nodegroup_name)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_nodegroup: {e}")))?;
        Ok(())
    }
}
