// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: elasticache
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn elasticache_replication_group_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "elasticache.ReplicationGroup".into(),
            description: "ReplicationGroup resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Replication group description".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("smelt managed")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Replication group ID".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "automatic_failover".into(),
                            description: "Enable automatic failover".into(),
                            field_type: crate::provider::FieldType::Bool,
                            required: false,
                            default: Some(serde_json::json!(false)),
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "engine".into(),
                                description: "Cache engine".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("redis")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "engine_version".into(),
                                description: "Engine version".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "node_type".into(),
                                description: "Cache node type (cache.t3.micro, etc.)".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "num_cache_clusters".into(),
                                description: "Number of cache clusters".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(1)),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_elasticache_replication_group(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let automatic_failover = config.bool_or("/reliability/automatic_failover", false);
        let description = config
            .str_or("/identity/description", "smelt managed")
            .to_string();
        let engine = config.str_or("/sizing/engine", "redis").to_string();
        let engine_version = config
            .optional_str("/sizing/engine_version")
            .map(String::from);
        let name = config.require_str("/identity/name")?.to_string();
        let node_type = config.require_str("/sizing/node_type")?.to_string();
        let num_cache_clusters = config.i64_or("/sizing/num_cache_clusters", 1);

        let tags = super::extract_tags(config);

        let mut req = self
            .elasticache_client
            .create_replication_group()
            .replication_group_id(&name)
            .cache_node_type(&node_type);

        req = req.automatic_failover_enabled(automatic_failover);
        req = req.replication_group_description(&description);
        req = req.engine(&engine);
        if let Some(ref v) = engine_version {
            req = req.engine_version(v);
        }
        req = req.num_cache_clusters(num_cache_clusters as i32);
        for (k, v) in &tags {
            req = req.tags(
                aws_sdk_elasticache::types::Tag::builder()
                    .key(k)
                    .value(v)
                    .build(),
            );
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_replication_group: {e}")))?;

        self.read_elasticache_replication_group(&name).await
    }

    pub(super) async fn read_elasticache_replication_group(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .elasticache_client
            .describe_replication_groups()
            .replication_group_id(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_replication_groups: {e}")))?;

        let resource = result
            .replication_groups()
            .first()
            .ok_or_else(|| ProviderError::NotFound(format!("ReplicationGroup {provider_id}")))?;

        let state = serde_json::json!({
            "identity": {
                "description": resource.description().unwrap_or(""),
                "name": provider_id,
            },
            "reliability": {
                "automatic_failover": resource.automatic_failover().map(|af| af.as_str() == "enabled").unwrap_or(false),
            },
            "sizing": {
                "node_type": resource.cache_node_type().unwrap_or(""),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "replication_group_id".into(),
            serde_json::json!(provider_id),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_elasticache_replication_group(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let automatic_failover = config.optional_bool("/reliability/automatic_failover");
        let description = config.optional_str("/identity/description");
        let node_type = config.optional_str("/sizing/node_type");

        let mut req = self
            .elasticache_client
            .modify_replication_group()
            .replication_group_id(provider_id);

        if let Some(v) = automatic_failover {
            req = req.automatic_failover_enabled(v);
        }
        if let Some(v) = description {
            req = req.replication_group_description(v);
        }
        if let Some(v) = node_type {
            req = req.cache_node_type(v);
        }

        req = req.apply_immediately(true);
        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("modify_replication_group: {e}")))?;

        self.read_elasticache_replication_group(provider_id).await
    }

    pub(super) async fn delete_elasticache_replication_group(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.elasticache_client
            .delete_replication_group()
            .replication_group_id(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_replication_group: {e}")))?;
        Ok(())
    }
}
