// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: kms
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn kms_key_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "kms.Key".into(),
            description: "Key resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Key description".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Key alias (becomes alias/name)".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "enabled".into(),
                                description: "Key enabled state".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "key_policy".into(),
                                description: "Key policy JSON".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "key_spec".into(),
                                description: "Key spec".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("SYMMETRIC_DEFAULT")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "key_usage".into(),
                                description: "Key usage type".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("ENCRYPT_DECRYPT")),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_kms_key(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let description = config
            .optional_str("/identity/description")
            .or_else(|| config.optional_str("/identity/name"))
            .unwrap_or("Managed by smelt");
        let key_usage = config.str_or("/security/key_usage", "ENCRYPT_DECRYPT");
        let key_spec = config.str_or("/security/key_spec", "SYMMETRIC_DEFAULT");

        let mut req = self
            .kms_client
            .create_key()
            .description(description)
            .key_usage(aws_sdk_kms::types::KeyUsageType::from(key_usage))
            .key_spec(aws_sdk_kms::types::KeySpec::from(key_spec));

        let tags = super::extract_tags(config);
        for (k, v) in &tags {
            req = req.tags(
                aws_sdk_kms::types::Tag::builder()
                    .tag_key(k)
                    .tag_value(v)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!("failed to build KMS Tag: {e}"))
                    })?,
            );
        }

        if let Some(policy) = config.optional_str("/security/key_policy") {
            req = req.policy(policy);
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_key: {e}")))?;

        let key = result
            .key_metadata()
            .ok_or_else(|| ProviderError::ApiError("CreateKey returned no metadata".into()))?;
        let provider_id = key.key_id();

        // Create alias if name is specified
        if let Some(name) = config.optional_str("/identity/name") {
            let alias = if name.starts_with("alias/") {
                name.to_string()
            } else {
                format!("alias/{name}")
            };
            self.kms_client
                .create_alias()
                .alias_name(&alias)
                .target_key_id(provider_id)
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("create_alias: {e}")))?;
        }

        self.read_kms_key(provider_id).await
    }

    pub(super) async fn read_kms_key(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .kms_client
            .describe_key()
            .key_id(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_key: {e}")))?;

        let resource = result
            .key_metadata()
            .ok_or_else(|| ProviderError::NotFound(format!("Key {provider_id}")))?;

        let mut state = serde_json::json!({
            "identity": {
                "name": provider_id,
            },
            "security": {
                "enabled": resource.enabled(),
                "key_spec": resource.key_spec().map(|r| r.as_str()).unwrap_or(""),
                "key_usage": resource.key_usage().map(|r| r.as_str()).unwrap_or(""),
            },
        });
        if let Some(val) = resource.description().filter(|s| !s.is_empty()) {
            state["identity"]["description"] = serde_json::json!(val);
        }

        let mut outputs = HashMap::new();
        outputs.insert("key_id".into(), serde_json::json!(resource.key_id()));
        outputs.insert(
            "key_arn".into(),
            serde_json::json!(resource.arn().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_kms_key(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        if let Some(desc) = config.optional_str("/identity/description") {
            self.kms_client
                .update_key_description()
                .key_id(provider_id)
                .description(desc)
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("update_key_description: {e}")))?;
        }

        if let Some(enabled) = config.optional_bool("/security/enabled") {
            if enabled {
                self.kms_client
                    .enable_key()
                    .key_id(provider_id)
                    .send()
                    .await
                    .map_err(|e| ProviderError::ApiError(format!("enable_key: {e}")))?;
            } else {
                self.kms_client
                    .disable_key()
                    .key_id(provider_id)
                    .send()
                    .await
                    .map_err(|e| ProviderError::ApiError(format!("disable_key: {e}")))?;
            }
        }

        self.read_kms_key(provider_id).await
    }

    pub(super) async fn delete_kms_key(&self, provider_id: &str) -> Result<(), ProviderError> {
        self.kms_client
            .schedule_key_deletion()
            .key_id(provider_id)
            .pending_window_in_days(30)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("schedule_key_deletion: {e}")))?;
        Ok(())
    }
}
