// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: lambda
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn lambda_function_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "lambda.Function".into(),
            description: "Function resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Function description".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Function name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "role_arn".into(),
                            description: "Execution IAM role ARN".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "handler".into(),
                                description: "Entry point handler".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("index.handler")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "memory_size".into(),
                                description: "Memory in MB (128-10240)".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(128)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "runtime".into(),
                                description: "Runtime (python3.12, nodejs20.x, etc.)".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "timeout".into(),
                                description: "Timeout in seconds (1-900)".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(30)),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_lambda_function(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let handler = config
            .str_or("/sizing/handler", "index.handler")
            .to_string();
        let memory_size = config.i64_or("/sizing/memory_size", 128);
        let name = config.require_str("/identity/name")?.to_string();
        let role_arn = config.require_str("/security/role_arn")?.to_string();
        let runtime = config.require_str("/sizing/runtime")?.to_string();
        let timeout = config.i64_or("/sizing/timeout", 30);

        let tags = super::extract_tags(config);

        let mut req = self
            .lambda_client
            .create_function()
            .function_name(&name)
            .role(&role_arn)
            .runtime(aws_sdk_lambda::types::Runtime::from(runtime.as_str()));

        if let Some(ref v) = description {
            req = req.description(v);
        }
        req = req.handler(&handler);
        req = req.memory_size(memory_size as i32);
        req = req.timeout(timeout as i32);
        req = req.set_tags(Some(tags));

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_function: {e}")))?;

        self.read_lambda_function(&name).await
    }

    pub(super) async fn read_lambda_function(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .lambda_client
            .get_function()
            .function_name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("get_function: {e}")))?;

        let resource = result
            .configuration()
            .ok_or_else(|| ProviderError::NotFound(format!("Function {provider_id}")))?;

        let state = serde_json::json!({
            "identity": {
                "description": resource.description().unwrap_or(""),
                "name": provider_id,
            },
            "security": {
                "role_arn": resource.role().unwrap_or(""),
            },
            "sizing": {
                "handler": resource.handler().unwrap_or(""),
                "memory_size": resource.memory_size().unwrap_or(0),
                "runtime": resource.runtime().map(|r| r.as_str()).unwrap_or(""),
                "timeout": resource.timeout().unwrap_or(0),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "function_arn".into(),
            serde_json::json!(resource.function_arn().unwrap_or("")),
        );
        outputs.insert(
            "function_name".into(),
            serde_json::json!(resource.function_name().unwrap_or("")),
        );
        outputs.insert(
            "last_modified".into(),
            serde_json::json!(resource.last_modified().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_lambda_function(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let description = config.optional_str("/identity/description");
        let handler = config.optional_str("/sizing/handler");
        let memory_size = config.optional_i64("/sizing/memory_size");
        let timeout = config.optional_i64("/sizing/timeout");

        let mut req = self
            .lambda_client
            .update_function_configuration()
            .function_name(provider_id);

        if let Some(v) = description {
            req = req.description(v);
        }
        if let Some(v) = handler {
            req = req.handler(v);
        }
        if let Some(v) = memory_size {
            req = req.memory_size(v as i32);
        }
        if let Some(v) = timeout {
            req = req.timeout(v as i32);
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("update_function_configuration: {e}")))?;

        self.read_lambda_function(provider_id).await
    }

    pub(super) async fn delete_lambda_function(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.lambda_client
            .delete_function()
            .function_name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_function: {e}")))?;
        Ok(())
    }
}
