// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: s3
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn s3_bucket_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "s3.Bucket".into(),
            description: "Bucket resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Globally unique bucket name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "tags".into(),
                                description: "Key-value tags".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: Some(serde_json::json!(null)),
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "versioning".into(),
                            description: "Enable object versioning".into(),
                            field_type: crate::provider::FieldType::Bool,
                            required: false,
                            default: Some(serde_json::json!(false)),
                            sensitive: false,
                        }],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![crate::provider::FieldSchema {
                            name: "encryption".into(),
                            description: "Server-side encryption (AES256 or aws:kms)".into(),
                            field_type: crate::provider::FieldType::String, /* Enum */
                            required: false,
                            default: Some(serde_json::json!("AES256")),
                            sensitive: false,
                        }],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_s3_bucket(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let name = config.require_str("/identity/name")?.to_string();

        let mut req = self.s3_client.create_bucket().bucket(&name);

        // S3 requires a location constraint for all regions except us-east-1
        let region = self
            .s3_client
            .config()
            .region()
            .map(|r| r.as_ref().to_string())
            .unwrap_or_default();
        if region != "us-east-1" && !region.is_empty() {
            req = req.create_bucket_configuration(
                aws_sdk_s3::types::CreateBucketConfiguration::builder()
                    .location_constraint(aws_sdk_s3::types::BucketLocationConstraint::from(
                        region.as_str(),
                    ))
                    .build(),
            );
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("CreateBucket: {e}")))?;

        // Enable versioning if requested
        if config
            .pointer("/reliability/versioning")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
        {
            self.s3_client
                .put_bucket_versioning()
                .bucket(&name)
                .versioning_configuration(
                    aws_sdk_s3::types::VersioningConfiguration::builder()
                        .status(aws_sdk_s3::types::BucketVersioningStatus::Enabled)
                        .build(),
                )
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("PutBucketVersioning: {e}")))?;
        }

        // Set encryption
        if let Some(algo) = config.optional_str("/security/encryption") {
            let sse = match algo {
                "AES256" => aws_sdk_s3::types::ServerSideEncryption::Aes256,
                _ => aws_sdk_s3::types::ServerSideEncryption::AwsKms,
            };
            self.s3_client
                .put_bucket_encryption()
                .bucket(&name)
                .server_side_encryption_configuration(
                    aws_sdk_s3::types::ServerSideEncryptionConfiguration::builder()
                        .rules(
                            aws_sdk_s3::types::ServerSideEncryptionRule::builder()
                                .apply_server_side_encryption_by_default(
                                    aws_sdk_s3::types::ServerSideEncryptionByDefault::builder()
                                        .sse_algorithm(sse)
                                        .build()
                                        .map_err(|e| {
                                            ProviderError::InvalidConfig(format!(
                                                "failed to build ServerSideEncryptionByDefault: {e}"
                                            ))
                                        })?,
                                )
                                .build(),
                        )
                        .build()
                        .map_err(|e| {
                            ProviderError::InvalidConfig(format!(
                                "failed to build ServerSideEncryptionConfiguration: {e}"
                            ))
                        })?,
                )
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("PutBucketEncryption: {e}")))?;
        }

        // Tags
        let tags = super::extract_tags(config);
        if !tags.is_empty() {
            let tag_set: Vec<aws_sdk_s3::types::Tag> = tags
                .iter()
                .map(|(k, v)| {
                    aws_sdk_s3::types::Tag::builder()
                        .key(k)
                        .value(v)
                        .build()
                        .map_err(|e| {
                            ProviderError::InvalidConfig(format!("failed to build S3 Tag: {e}"))
                        })
                })
                .collect::<Result<Vec<_>, _>>()?;
            self.s3_client
                .put_bucket_tagging()
                .bucket(&name)
                .tagging(
                    aws_sdk_s3::types::Tagging::builder()
                        .set_tag_set(Some(tag_set))
                        .build()
                        .map_err(|e| {
                            ProviderError::InvalidConfig(format!("failed to build Tagging: {e}"))
                        })?,
                )
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("PutBucketTagging: {e}")))?;
        }

        let provider_id = &name;

        self.read_s3_bucket(provider_id).await
    }

    pub(super) async fn read_s3_bucket(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        // Verify bucket exists
        self.s3_client
            .head_bucket()
            .bucket(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("HeadBucket: {e}")))?;

        let mut versioning = false;
        if let Ok(v) = self
            .s3_client
            .get_bucket_versioning()
            .bucket(provider_id)
            .send()
            .await
        {
            versioning = v.status() == Some(&aws_sdk_s3::types::BucketVersioningStatus::Enabled);
        }

        let state = serde_json::json!({
            "identity": { "name": provider_id },
            "reliability": { "versioning": versioning },
        });

        let mut outputs = HashMap::new();
        outputs.insert("bucket_name".into(), serde_json::json!(provider_id));
        outputs.insert(
            "bucket_arn".into(),
            serde_json::json!(format!("arn:aws:s3:::{provider_id}")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_s3_bucket(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        if let Some(v) = config
            .pointer("/reliability/versioning")
            .and_then(|v| v.as_bool())
        {
            let status = if v {
                aws_sdk_s3::types::BucketVersioningStatus::Enabled
            } else {
                aws_sdk_s3::types::BucketVersioningStatus::Suspended
            };
            self.s3_client
                .put_bucket_versioning()
                .bucket(provider_id)
                .versioning_configuration(
                    aws_sdk_s3::types::VersioningConfiguration::builder()
                        .status(status)
                        .build(),
                )
                .send()
                .await
                .map_err(|e| ProviderError::ApiError(format!("PutBucketVersioning: {e}")))?;
        }

        self.read_s3_bucket(provider_id).await
    }

    pub(super) async fn delete_s3_bucket(&self, provider_id: &str) -> Result<(), ProviderError> {
        self.s3_client
            .delete_bucket()
            .bucket(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DeleteBucket: {e}")))?;
        Ok(())
    }
}
