// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: sns
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn sns_topic_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "sns.Topic".into(),
            description: "Topic resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![crate::provider::SectionSchema {
                    name: "identity".into(),
                    description: "Identity configuration".into(),
                    fields: vec![
                        crate::provider::FieldSchema {
                            name: "fifo".into(),
                            description: "FIFO topic".into(),
                            field_type: crate::provider::FieldType::Bool,
                            required: false,
                            default: Some(serde_json::json!(false)),
                            sensitive: false,
                        },
                        crate::provider::FieldSchema {
                            name: "name".into(),
                            description: "Topic name".into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        },
                    ],
                }],
            },
        }
    }

    pub(super) async fn create_sns_topic(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let fifo = config.bool_or("/identity/fifo", false);
        let name = config.require_str("/identity/name")?.to_string();

        let tags = super::extract_tags(config);

        let mut req = self.sns_client.create_topic().name(&name);

        if fifo {
            req = req.attributes("FifoTopic", "true");
        }
        for (k, v) in &tags {
            req = req.tags(
                aws_sdk_sns::types::Tag::builder()
                    .key(k)
                    .value(v)
                    .build()
                    .map_err(|e| {
                        ProviderError::InvalidConfig(format!("failed to build Tag: {e}"))
                    })?,
            );
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_topic: {e}")))?;

        let provider_id = result
            .topic_arn()
            .ok_or_else(|| ProviderError::ApiError("create_topic returned no topic_arn".into()))?;

        self.read_sns_topic(provider_id).await
    }

    pub(super) async fn read_sns_topic(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .sns_client
            .get_topic_attributes()
            .topic_arn(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("get_topic_attributes: {e}")))?;

        let attrs = result.attributes().cloned().unwrap_or_default();

        let state = serde_json::json!({
            "identity": {
                "fifo": attrs.get("FifoTopic").map(|v| v == "true").unwrap_or(false),
                "name": provider_id.rsplit(':').next().unwrap_or(""),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("topic_arn".into(), serde_json::json!(provider_id));
        outputs.insert(
            "topic_name".into(),
            serde_json::json!(provider_id.rsplit(':').next().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    #[allow(dead_code)]
    pub(super) async fn update_sns_topic(
        &self,
        _provider_id: &str,
        _config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        Err(ProviderError::RequiresReplacement(
            "resource does not support in-place update".into(),
        ))
    }

    pub(super) async fn delete_sns_topic(&self, provider_id: &str) -> Result<(), ProviderError> {
        self.sns_client
            .delete_topic()
            .topic_arn(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_topic: {e}")))?;
        Ok(())
    }
}
