// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: sqs
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn sqs_queue_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "sqs.Queue".into(),
            description: "Queue resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "fifo".into(),
                                description: "FIFO queue".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: Some(serde_json::json!(false)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Queue name".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "delay_seconds".into(),
                                description: "Delivery delay in seconds (0–900)".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(0)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "message_retention_seconds".into(),
                                description: "Message retention period in seconds (60–1209600)".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(345600)),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "visibility_timeout".into(),
                                description: "Visibility timeout in seconds (0–43200)".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(30)),
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_sqs_queue(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let delay_seconds = config.i64_or("/reliability/delay_seconds", 0);
        let fifo = config.bool_or("/identity/fifo", false);
        let message_retention_seconds = config.i64_or("/reliability/message_retention_seconds", 345600);
        let name = config.require_str("/identity/name")?.to_string();
        let visibility_timeout = config.i64_or("/reliability/visibility_timeout", 30);

        let tags = super::extract_tags(config);

        let mut req = self.sqs_client
            .create_queue()
            .queue_name(&name)
        ;

        req = req.attributes("DelaySeconds".into(), delay_seconds.to_string());
        if fifo {
            req = req.attributes("FifoQueue".into(), "true");
        }
        req = req.attributes("MessageRetentionPeriod".into(), message_retention_seconds.to_string());
        req = req.attributes("VisibilityTimeout".into(), visibility_timeout.to_string());
        for (k, v) in &tags {
            req = req.tags(k, v);
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_queue: {e}")))?;

        let provider_id = result
            .queue_url()
            .ok_or_else(|| ProviderError::ApiError("create_queue returned no queue_url".into()))?;

        self.read_sqs_queue(provider_id).await
    }

    pub(super) async fn read_sqs_queue(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self.sqs_client
            .get_queue_attributes()
            .queue_url(provider_id)
            .attribute_names(aws_sdk_sqs::types::QueueAttributeName::All)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("get_queue_attributes: {e}")))?;


        let attrs = result.attributes().cloned().unwrap_or_default();

        let state = serde_json::json!({
            "identity": {
                "fifo": attrs.get(&aws_sdk_sqs::types::QueueAttributeName::FifoQueue).map(|v| v == "true").unwrap_or(false),
                "name": provider_id.rsplit('/').next().unwrap_or(""),
            },
            "reliability": {
                "delay_seconds": attrs.get(&aws_sdk_sqs::types::QueueAttributeName::DelaySeconds).and_then(|v| v.parse::<i64>().ok()).unwrap_or(0),
                "message_retention_seconds": attrs.get(&aws_sdk_sqs::types::QueueAttributeName::MessageRetentionPeriod).and_then(|v| v.parse::<i64>().ok()).unwrap_or(0),
                "visibility_timeout": attrs.get(&aws_sdk_sqs::types::QueueAttributeName::VisibilityTimeout).and_then(|v| v.parse::<i64>().ok()).unwrap_or(0),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("queue_url".into(), serde_json::json!(provider_id));
        outputs.insert("queue_arn".into(), serde_json::json!(attrs.get(&aws_sdk_sqs::types::QueueAttributeName::QueueArn).cloned().unwrap_or_default()));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_sqs_queue(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let delay_seconds = config.optional_i64("/reliability/delay_seconds");
        let fifo = config.optional_bool("/identity/fifo");
        let message_retention_seconds = config.optional_i64("/reliability/message_retention_seconds");
        let visibility_timeout = config.optional_i64("/reliability/visibility_timeout");

        let mut req = self.sqs_client
            .set_queue_attributes()
            .queue_url(provider_id)
        ;

        if let Some(v) = delay_seconds {
            req = req.attributes("DelaySeconds".into(), v.to_string());
        }
        if let Some(true) = fifo {
            req = req.attributes("FifoQueue".into(), "true");
        }
        if let Some(v) = message_retention_seconds {
            req = req.attributes("MessageRetentionPeriod".into(), v.to_string());
        }
        if let Some(v) = visibility_timeout {
            req = req.attributes("VisibilityTimeout".into(), v.to_string());
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("set_queue_attributes: {e}")))?;

        self.read_sqs_queue(provider_id).await
    }

    pub(super) async fn delete_sqs_queue(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.sqs_client
            .delete_queue()
            .queue_url(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_queue: {e}")))?;
        Ok(())
    }


}
