// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: ssm
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn ssm_parameter_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "ssm.Parameter".into(),
            description: "Parameter resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Parameter description".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description:
                                    "Parameter name (path-style recommended, e.g., /app/config/key)"
                                        .into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "tier".into(),
                                description: "Parameter tier (Standard or Advanced)".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("Standard")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "type".into(),
                                description: "Parameter type".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: Some(serde_json::json!("String")),
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "value".into(),
                                description: "Parameter value".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_ssm_parameter(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let name = config.require_str("/identity/name")?.to_string();
        let tier = config.str_or("/sizing/tier", "Standard").to_string();
        let type_val = config.str_or("/sizing/type", "String").to_string();
        let value = config.require_str("/sizing/value")?.to_string();

        let mut req = self.ssm_client.put_parameter().name(&name).value(&value);

        if let Some(ref v) = description {
            req = req.description(v);
        }
        req = req.tier(aws_sdk_ssm::types::ParameterTier::from(tier.as_str()));
        req = req.r#type(aws_sdk_ssm::types::ParameterType::from(type_val.as_str()));

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("put_parameter: {e}")))?;

        self.read_ssm_parameter(&name).await
    }

    pub(super) async fn read_ssm_parameter(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .ssm_client
            .get_parameter()
            .name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("get_parameter: {e}")))?;

        let resource = result
            .parameter()
            .ok_or_else(|| ProviderError::NotFound(format!("Parameter {provider_id}")))?;

        // describe_parameters returns description + tier (get_parameter does not)
        let desc_result = self
            .ssm_client
            .describe_parameters()
            .parameter_filters(
                aws_sdk_ssm::types::ParameterStringFilter::builder()
                    .key("Name")
                    .values(provider_id)
                    .build()
                    .map_err(|e| ProviderError::ApiError(format!("filter build: {e}")))?,
            )
            .send()
            .await
            .ok();
        let param_meta = desc_result.as_ref().and_then(|r| r.parameters().first());

        let mut identity = serde_json::json!({ "name": provider_id });
        if let Some(desc) = param_meta
            .and_then(|p| p.description())
            .filter(|s| !s.is_empty())
        {
            identity["description"] = serde_json::json!(desc);
        }

        let mut sizing = serde_json::json!({
            "type": resource.r#type().map(|r| r.as_str()).unwrap_or(""),
            "value": resource.value().unwrap_or(""),
        });
        if let Some(tier) = param_meta.and_then(|p| p.tier()).map(|t| t.as_str()) {
            sizing["tier"] = serde_json::json!(tier);
        }

        let state = serde_json::json!({
            "identity": identity,
            "sizing": sizing,
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "parameter_name".into(),
            serde_json::json!(resource.name().unwrap_or("")),
        );
        outputs.insert(
            "parameter_arn".into(),
            serde_json::json!(resource.arn().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_ssm_parameter(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let description = config.optional_str("/identity/description");
        let tier = config.optional_str("/sizing/tier");
        let type_val = config.optional_str("/sizing/type");
        let value = config.optional_str("/sizing/value");

        let mut req = self.ssm_client.put_parameter().name(provider_id);

        if let Some(v) = description {
            req = req.description(v);
        }
        if let Some(v) = tier {
            req = req.tier(aws_sdk_ssm::types::ParameterTier::from(v));
        }
        if let Some(v) = type_val {
            req = req.r#type(aws_sdk_ssm::types::ParameterType::from(v));
        }
        if let Some(v) = value {
            req = req.value(v);
        }

        req = req.overwrite(true);
        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("put_parameter: {e}")))?;

        self.read_ssm_parameter(provider_id).await
    }

    pub(super) async fn delete_ssm_parameter(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.ssm_client
            .delete_parameter()
            .name(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_parameter: {e}")))?;
        Ok(())
    }
}
