// Generated by smelt-codegen batch — do not edit by hand.
// Service: filestore
// Resources: 2

use smelt_provider::*;
use std::collections::HashMap;

use super::GcpProvider;
use google_cloud_lro::Poller;

impl GcpProvider {
    pub(super) fn filestore_instance_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "filestore.Instance".into(),
            description: "Instance resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "description".into(),
                                description: "The description of the instance (2048 characters or less).".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "labels".into(),
                                description: "Resource labels to represent user provided metadata.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The resource name of the instance, in the format".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "tags".into(),
                                description: "Optional. Input only. Immutable. Tag key-value pairs bound to this".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "deletion_protection_enabled".into(),
                                description: "Optional. Indicates whether the instance is protected against deletion.".into(),
                                field_type: smelt_provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "deletion_protection_reason".into(),
                                description: "Optional. The reason for enabling deletion protection.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "file_shares".into(),
                                description: "File system shares on the instance.".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "networks".into(),
                                description: "VPC networks to which the instance is connected.".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "performance_config".into(),
                                description: "Optional. Used to configure performance.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "protocol".into(),
                                description: "Immutable. The protocol indicates the access protocol for all shares in the".into(),
                                field_type: smelt_provider::FieldType::Enum(vec!["FILE_PROTOCOL_UNSPECIFIED".into(), "NFS_V3".into(), "NFS_V4_1".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "tier".into(),
                                description: "The service tier of the instance.".into(),
                                field_type: smelt_provider::FieldType::Enum(vec!["TIER_UNSPECIFIED".into(), "STANDARD".into(), "PREMIUM".into(), "BASIC_HDD".into(), "BASIC_SSD".into(), "HIGH_SCALE_SSD".into(), "ENTERPRISE".into(), "ZONAL".into(), "REGIONAL".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "replication".into(),
                                description: "Optional. Replication configuration.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "kms_key_name".into(),
                                description: "KMS key name used for data encryption.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_filestore_instance(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let deletion_protection_enabled =
            config.optional_bool("/config/deletion_protection_enabled");
        let deletion_protection_reason = config
            .optional_str("/config/deletion_protection_reason")
            .map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let file_shares = config.pointer("/config/file_shares").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_filestore_v1::model::FileShareConfig>>(
                v.clone(),
            )
            .ok()
        });
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let networks = config.pointer("/config/networks").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_filestore_v1::model::NetworkConfig>>(
                v.clone(),
            )
            .ok()
        });
        let performance_config = config.pointer("/config/performance_config").and_then(|v| {
            serde_json::from_value::<google_cloud_filestore_v1::model::instance::PerformanceConfig>(
                v.clone(),
            )
            .ok()
        });
        let protocol = config.optional_str("/config/protocol").map(String::from);
        let replication = config.pointer("/reliability/replication").and_then(|v| {
            serde_json::from_value::<google_cloud_filestore_v1::model::Replication>(v.clone()).ok()
        });
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let tier = config.optional_str("/config/tier").map(String::from);

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_filestore_v1::model::Instance::default();
        if let Some(v) = deletion_protection_enabled {
            model = model.set_deletion_protection_enabled(v);
        }
        if let Some(v) = deletion_protection_reason {
            model = model.set_deletion_protection_reason(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = file_shares {
            model = model.set_file_shares(v);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        // Do NOT set name on model — Filestore infers it from instance_id
        if let Some(v) = networks {
            model = model.set_networks(v);
        }
        if let Some(v) = performance_config {
            model = model.set_performance_config(v);
        }
        if let Some(ref s) = protocol {
            model = model.set_protocol(
                google_cloud_filestore_v1::model::instance::FileProtocol::from(s.as_str()),
            );
        }
        if let Some(v) = replication {
            model = model.set_replication(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(ref s) = tier {
            model = model.set_tier(google_cloud_filestore_v1::model::instance::Tier::from(
                s.as_str(),
            ));
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.cloud_filestore_manager()
            .await?
            .create_instance()
            .set_parent(&parent)
            .set_instance_id(&name)
            .set_instance(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_instance Instance", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/instances/{}",
            self.project_id, self.region, name
        );
        self.read_filestore_instance(&provider_id).await
    }

    pub(super) async fn read_filestore_instance(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let instance = self
            .cloud_filestore_manager()
            .await?
            .get_instance()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetInstance", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = instance
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": instance.description.as_str(),
                "labels": user_labels,
                "name": instance.name.as_str(),
                "tags": &instance.tags,
            },
            "config": {
                "deletion_protection_enabled": instance.deletion_protection_enabled,
                "deletion_protection_reason": instance.deletion_protection_reason.as_str(),
                "file_shares": &instance.file_shares,
                "networks": &instance.networks,
                "performance_config": &instance.performance_config,
                "protocol": &instance.protocol,
                "tier": &instance.tier,
            },
            "reliability": {
                "replication": &instance.replication,
            },
            "security": {
                "kms_key_name": instance.kms_key_name.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&instance.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_filestore_instance(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let deletion_protection_enabled =
            config.optional_bool("/config/deletion_protection_enabled");
        let deletion_protection_reason = config
            .optional_str("/config/deletion_protection_reason")
            .map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let file_shares = config.pointer("/config/file_shares").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_filestore_v1::model::FileShareConfig>>(
                v.clone(),
            )
            .ok()
        });
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let networks = config.pointer("/config/networks").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_filestore_v1::model::NetworkConfig>>(
                v.clone(),
            )
            .ok()
        });
        let performance_config = config.pointer("/config/performance_config").and_then(|v| {
            serde_json::from_value::<google_cloud_filestore_v1::model::instance::PerformanceConfig>(
                v.clone(),
            )
            .ok()
        });
        let protocol = config.optional_str("/config/protocol").map(String::from);
        let replication = config.pointer("/reliability/replication").and_then(|v| {
            serde_json::from_value::<google_cloud_filestore_v1::model::Replication>(v.clone()).ok()
        });
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let tier = config.optional_str("/config/tier").map(String::from);
        let labels = super::extract_labels(config);

        let mut model = google_cloud_filestore_v1::model::Instance::default();
        model = model.set_name(provider_id);
        if let Some(v) = deletion_protection_enabled {
            model = model.set_deletion_protection_enabled(v);
        }
        if let Some(v) = deletion_protection_reason {
            model = model.set_deletion_protection_reason(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = file_shares {
            model = model.set_file_shares(v);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        if let Some(v) = networks {
            model = model.set_networks(v);
        }
        if let Some(v) = performance_config {
            model = model.set_performance_config(v);
        }
        if let Some(ref s) = protocol {
            model = model.set_protocol(
                google_cloud_filestore_v1::model::instance::FileProtocol::from(s.as_str()),
            );
        }
        if let Some(v) = replication {
            model = model.set_replication(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(ref s) = tier {
            model = model.set_tier(google_cloud_filestore_v1::model::instance::Tier::from(
                s.as_str(),
            ));
        }
        model = model.set_labels(labels);

        self.cloud_filestore_manager()
            .await?
            .update_instance()
            .set_instance(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_instance Instance", e))?;

        self.read_filestore_instance(provider_id).await
    }

    pub(super) async fn delete_filestore_instance(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.cloud_filestore_manager()
            .await?
            .delete_instance()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteInstance", e))?;
        Ok(())
    }

    pub(super) fn filestore_backup_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "filestore.Backup".into(),
            description: "Backup resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "description".into(),
                                description: "A description of the backup with 2048 characters or less.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "labels".into(),
                                description: "Resource labels to represent user provided metadata.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The resource name of the backup, in the format".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "tags".into(),
                                description: "Optional. Input only. Immutable. Tag key-value pairs bound to this".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "kms_key".into(),
                                description: "Immutable. KMS key name used for data encryption.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "source_file_share".into(),
                                description: "Name of the file share in the source Filestore instance that the".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "source_instance".into(),
                                description: "The resource name of the source Filestore instance, in the format".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_filestore_backup(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let kms_key = config.optional_str("/config/kms_key").map(String::from);
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let source_file_share = config
            .optional_str("/config/source_file_share")
            .map(String::from);
        let source_instance = config
            .optional_str("/config/source_instance")
            .map(String::from);
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_filestore_v1::model::Backup::default();
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = kms_key {
            model = model.set_kms_key(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = source_file_share {
            model = model.set_source_file_share(v);
        }
        if let Some(v) = source_instance {
            model = model.set_source_instance(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.cloud_filestore_manager()
            .await?
            .create_backup()
            .set_parent(&parent)
            .set_backup_id(&name)
            .set_backup(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_backup Backup", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/backups/{}",
            self.project_id, self.region, name
        );
        self.read_filestore_backup(&provider_id).await
    }

    pub(super) async fn read_filestore_backup(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let backup = self
            .cloud_filestore_manager()
            .await?
            .get_backup()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetBackup", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = backup
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": backup.description.as_str(),
                "labels": user_labels,
                "name": backup.name.as_str(),
                "tags": &backup.tags,
            },
            "config": {
                "kms_key": backup.kms_key.as_str(),
                "source_file_share": backup.source_file_share.as_str(),
                "source_instance": backup.source_instance.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&backup.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_filestore_backup(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let kms_key = config.optional_str("/config/kms_key").map(String::from);
        let source_file_share = config
            .optional_str("/config/source_file_share")
            .map(String::from);
        let source_instance = config
            .optional_str("/config/source_instance")
            .map(String::from);
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let labels = super::extract_labels(config);

        let mut model = google_cloud_filestore_v1::model::Backup::default();
        model = model.set_name(provider_id);
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = kms_key {
            model = model.set_kms_key(v);
        }
        if let Some(v) = source_file_share {
            model = model.set_source_file_share(v);
        }
        if let Some(v) = source_instance {
            model = model.set_source_instance(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        model = model.set_labels(labels);

        self.cloud_filestore_manager()
            .await?
            .update_backup()
            .set_backup(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_backup Backup", e))?;

        self.read_filestore_backup(provider_id).await
    }

    pub(super) async fn delete_filestore_backup(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.cloud_filestore_manager()
            .await?
            .delete_backup()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteBackup", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn filestore_instance_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn filestore_backup_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
