// Generated by smelt-codegen batch — do not edit by hand.
// Service: iam
// Resources: 2

use smelt_provider::*;
use std::collections::HashMap;

use super::GcpProvider;

/// Extract the short account ID from a service account email or full resource path.
/// e.g., "projects/p/serviceAccounts/foo@p.iam.gserviceaccount.com" → "foo"
/// e.g., "foo@p.iam.gserviceaccount.com" → "foo"
/// e.g., "foo" → "foo"
fn service_account_to_id(provider_id: &str) -> &str {
    // Try email format: take everything before @
    let last_segment = provider_id.rsplit('/').next().unwrap_or(provider_id);
    last_segment.split('@').next().unwrap_or(last_segment)
}

impl GcpProvider {
    pub(super) fn iam_serviceaccount_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "iam.ServiceAccount".into(),
            description: "ServiceAccount resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "description".into(),
                                description: "Optional. A user-specified, human-readable description of the service account. The".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "display_name".into(),
                                description: "Optional. A user-specified, human-readable name for the service account. The maximum".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "The resource name of the service account.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_iam_serviceaccount(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let name = config.require_str("/identity/name")?.to_string();

        // Build SDK model
        let mut model = google_cloud_iam_admin_v1::model::ServiceAccount::default();
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        // Do NOT set model.name on create — GCP auto-assigns it.

        // Make API call
        let parent = format!("projects/{}", self.project_id);
        let created = self
            .iam()
            .await?
            .create_service_account()
            .set_name(&parent)
            .set_account_id(&name)
            .set_service_account(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_service_account ServiceAccount", e))?;

        let provider_id = created.name.clone();
        // Retry read-back: IAM has significant eventual consistency (up to ~10s)
        for attempt in 0..5u32 {
            match self.read_iam_serviceaccount(&provider_id).await {
                Ok(result) => return Ok(result),
                Err(ProviderError::NotFound(_)) if attempt < 4 => {
                    tokio::time::sleep(std::time::Duration::from_millis(
                        1000 * (attempt as u64 + 1),
                    ))
                    .await;
                }
                Err(e) => return Err(e),
            }
        }
        self.read_iam_serviceaccount(&provider_id).await
    }

    pub(super) async fn read_iam_serviceaccount(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract short account ID from full path (projects/.../serviceAccounts/email)
        let account_id = service_account_to_id(provider_id);
        let service_account = self
            .iam()
            .await?
            .get_service_account()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetServiceAccount", e))?;

        let mut state = serde_json::json!({
            "identity": {
                "name": account_id,
            },
        });
        let desc = service_account.description.as_str();
        if !desc.is_empty() {
            state["identity"]["description"] = serde_json::json!(desc);
        }
        let dn = service_account.display_name.as_str();
        if !dn.is_empty() {
            state["identity"]["display_name"] = serde_json::json!(dn);
        }

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&service_account.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_iam_serviceaccount(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);

        let mut model = google_cloud_iam_admin_v1::model::ServiceAccount::default();
        model = model.set_name(provider_id);
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }

        self.iam()
            .await?
            .patch_service_account()
            .set_service_account(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("patch_service_account ServiceAccount", e))?;

        self.read_iam_serviceaccount(provider_id).await
    }

    pub(super) async fn delete_iam_serviceaccount(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.iam()
            .await?
            .delete_service_account()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteServiceAccount", e))?;
        Ok(())
    }

    pub(super) fn iam_role_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "iam.Role".into(),
            description: "Role resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "description".into(),
                                description: "Optional. A human-readable description for the role.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "The name of the role.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "deleted".into(),
                                description: "The current deleted state of the role. This field is read only.".into(),
                                field_type: smelt_provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "included_permissions".into(),
                                description: "The names of the permissions this role grants when bound in an IAM policy.".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::String)),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "stage".into(),
                                description: "The current launch stage of the role. If the `ALPHA` launch stage has been".into(),
                                field_type: smelt_provider::FieldType::Enum(vec!["ALPHA".into(), "BETA".into(), "GA".into(), "DEPRECATED".into(), "DISABLED".into(), "EAP".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "title".into(),
                                description: "Optional. A human-readable title for the role.  Typically this".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_iam_role(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let deleted = config.optional_bool("/config/deleted");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let included_permissions = config
            .pointer("/config/included_permissions")
            .and_then(|v| serde_json::from_value::<Vec<String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let stage = config.optional_str("/config/stage").map(String::from);
        let title = config.optional_str("/config/title").map(String::from);

        // Build SDK model
        let mut model = google_cloud_iam_admin_v1::model::Role::default();
        if let Some(v) = deleted {
            model = model.set_deleted(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = included_permissions {
            model = model.set_included_permissions(v);
        }
        // Do NOT set model.name on create — name passed via set_role_id on request
        if let Some(ref s) = stage {
            model = model.set_stage(
                google_cloud_iam_admin_v1::model::role::RoleLaunchStage::from(s.as_str()),
            );
        }
        if let Some(v) = title {
            model = model.set_title(v);
        }

        // Make API call
        let parent = format!("projects/{}", self.project_id);
        self.iam()
            .await?
            .create_role()
            .set_parent(&parent)
            .set_role_id(&name)
            .set_role(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_role Role", e))?;

        let provider_id = format!("projects/{}/roles/{}", self.project_id, name);
        self.read_iam_role(&provider_id).await
    }

    pub(super) async fn read_iam_role(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let role = self
            .iam()
            .await?
            .get_role()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetRole", e))?;

        let short_name = provider_id.rsplit('/').next().unwrap_or(provider_id);
        let mut state = serde_json::json!({
            "identity": {
                "name": short_name,
            },
            "security": {
                "included_permissions": &role.included_permissions,
                "stage": format!("{:?}", role.stage).to_uppercase(),
            },
        });
        let desc = role.description.as_str();
        if !desc.is_empty() {
            state["identity"]["description"] = serde_json::json!(desc);
        }
        let title = role.title.as_str();
        if !title.is_empty() {
            state["identity"]["title"] = serde_json::json!(title);
        }

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&role.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_iam_role(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let deleted = config.optional_bool("/config/deleted");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let included_permissions = config
            .pointer("/config/included_permissions")
            .and_then(|v| serde_json::from_value::<Vec<String>>(v.clone()).ok());
        let stage = config.optional_str("/config/stage").map(String::from);
        let title = config.optional_str("/config/title").map(String::from);

        let mut model = google_cloud_iam_admin_v1::model::Role::default();
        model = model.set_name(provider_id);
        if let Some(v) = deleted {
            model = model.set_deleted(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = included_permissions {
            model = model.set_included_permissions(v);
        }
        if let Some(ref s) = stage {
            model = model.set_stage(
                google_cloud_iam_admin_v1::model::role::RoleLaunchStage::from(s.as_str()),
            );
        }
        if let Some(v) = title {
            model = model.set_title(v);
        }

        self.iam()
            .await?
            .update_role()
            .set_role(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_role Role", e))?;

        self.read_iam_role(provider_id).await
    }

    pub(super) async fn delete_iam_role(&self, provider_id: &str) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.iam()
            .await?
            .delete_role()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteRole", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn iam_serviceaccount_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn iam_role_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
