// Generated by smelt-codegen batch — do not edit by hand.
// Service: secretmanager
// Resources: 1

use smelt_provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn secretmanager_secret_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "secretmanager.Secret".into(),
            description: "Secret resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "labels".into(),
                                description: "The labels assigned to this Secret.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The resource name of the".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "tags".into(),
                                description: "Optional. Input only. Immutable. Mapping of Tag keys/values directly bound".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "annotations".into(),
                                description: "Optional. Custom metadata about the secret.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "customer_managed_encryption".into(),
                                description: "Optional. The customer-managed encryption configuration of the regionalized".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "expiration".into(),
                                description: "Expiration policy attached to the".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "rotation".into(),
                                description: "Optional. Rotation policy attached to the".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "topics".into(),
                                description: "Optional. A list of up to 10 Pub/Sub topics to which messages are published".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "version_aliases".into(),
                                description: "Optional. Mapping from version alias to version name.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "version_destroy_ttl".into(),
                                description: "Optional. Secret Version TTL after destruction request".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "replication".into(),
                                description: "Optional. Immutable. The replication policy of the secret data attached to".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_secretmanager_secret(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let customer_managed_encryption = config
            .pointer("/config/customer_managed_encryption")
            .and_then(|v| {
                serde_json::from_value::<
                    google_cloud_secretmanager_v1::model::CustomerManagedEncryption,
                >(v.clone())
                .ok()
            });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let replication = config.pointer("/reliability/replication").and_then(|v| {
            serde_json::from_value::<google_cloud_secretmanager_v1::model::Replication>(v.clone())
                .ok()
        });
        let rotation = config.pointer("/config/rotation").and_then(|v| {
            serde_json::from_value::<google_cloud_secretmanager_v1::model::Rotation>(v.clone()).ok()
        });
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let topics = config.pointer("/config/topics").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_secretmanager_v1::model::Topic>>(v.clone())
                .ok()
        });
        let version_aliases = config
            .pointer("/config/version_aliases")
            .and_then(|v| serde_json::from_value::<HashMap<String, i64>>(v.clone()).ok());
        let version_destroy_ttl = config
            .pointer("/config/version_destroy_ttl")
            .and_then(|v| serde_json::from_value::<google_cloud_wkt::Duration>(v.clone()).ok());

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_secretmanager_v1::model::Secret::default();
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = customer_managed_encryption {
            model = model.set_customer_managed_encryption(v);
        }
        if let Some(v) = config.optional_str("/config/expire_time") {
            model = model.set_expire_time(
                google_cloud_wkt::Timestamp::try_from(v)
                    .map_err(|e| ProviderError::InvalidConfig(format!("expire_time: {e}")))?,
            );
        } else if let Some(v) = config.optional_str("/config/ttl") {
            model = model.set_ttl(
                google_cloud_wkt::Duration::try_from(v)
                    .map_err(|e| ProviderError::InvalidConfig(format!("ttl: {e}")))?,
            );
        }
        model = model.set_name(name.clone());
        if let Some(v) = replication {
            model = model.set_replication(v);
        }
        if let Some(v) = rotation {
            model = model.set_rotation(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(v) = topics {
            model = model.set_topics(v);
        }
        if let Some(v) = version_aliases {
            model = model.set_version_aliases(v);
        }
        if let Some(v) = version_destroy_ttl {
            model = model.set_version_destroy_ttl(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}", self.project_id);
        self.secretmanager()
            .await?
            .create_secret()
            .set_parent(&parent)
            .set_secret_id(&name)
            .set_secret(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_secret Secret", e))?;

        let provider_id = format!("projects/{}/secrets/{}", self.project_id, name);
        self.read_secretmanager_secret(&provider_id).await
    }

    pub(super) async fn read_secretmanager_secret(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let secret = self
            .secretmanager()
            .await?
            .get_secret()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetSecret", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = secret
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        // Extract short name from full resource path
        let short_name = provider_id.rsplit('/').next().unwrap_or(provider_id);

        let mut state = serde_json::json!({
            "identity": {
                "name": short_name,
            },
        });
        if !user_labels.is_empty() {
            state["identity"]["labels"] = serde_json::Value::Object(user_labels);
        }
        // Only include replication if user-managed (non-default).
        // GCP always returns automatic replication as the default;
        // only user_managed replication is user-configurable state.
        if let Some(ref repl) = secret.replication {
            let repl_json = serde_json::to_value(repl).unwrap_or_default();
            if repl_json.get("user_managed").is_some() || repl_json.get("userManaged").is_some() {
                state["reliability"] = serde_json::json!({
                    "replication": repl_json,
                });
            }
        }

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&secret.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_secretmanager_secret(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let customer_managed_encryption = config
            .pointer("/config/customer_managed_encryption")
            .and_then(|v| {
                serde_json::from_value::<
                    google_cloud_secretmanager_v1::model::CustomerManagedEncryption,
                >(v.clone())
                .ok()
            });
        let replication = config.pointer("/reliability/replication").and_then(|v| {
            serde_json::from_value::<google_cloud_secretmanager_v1::model::Replication>(v.clone())
                .ok()
        });
        let rotation = config.pointer("/config/rotation").and_then(|v| {
            serde_json::from_value::<google_cloud_secretmanager_v1::model::Rotation>(v.clone()).ok()
        });
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let topics = config.pointer("/config/topics").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_secretmanager_v1::model::Topic>>(v.clone())
                .ok()
        });
        let version_aliases = config
            .pointer("/config/version_aliases")
            .and_then(|v| serde_json::from_value::<HashMap<String, i64>>(v.clone()).ok());
        let version_destroy_ttl = config
            .pointer("/config/version_destroy_ttl")
            .and_then(|v| serde_json::from_value::<google_cloud_wkt::Duration>(v.clone()).ok());
        let labels = super::extract_labels(config);

        let mut model = google_cloud_secretmanager_v1::model::Secret::default();
        model = model.set_name(provider_id);
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = customer_managed_encryption {
            model = model.set_customer_managed_encryption(v);
        }
        if let Some(v) = config.optional_str("/config/expire_time") {
            model = model.set_expire_time(
                google_cloud_wkt::Timestamp::try_from(v)
                    .map_err(|e| ProviderError::InvalidConfig(format!("expire_time: {e}")))?,
            );
        } else if let Some(v) = config.optional_str("/config/ttl") {
            model = model.set_ttl(
                google_cloud_wkt::Duration::try_from(v)
                    .map_err(|e| ProviderError::InvalidConfig(format!("ttl: {e}")))?,
            );
        }
        if let Some(v) = replication {
            model = model.set_replication(v);
        }
        if let Some(v) = rotation {
            model = model.set_rotation(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(v) = topics {
            model = model.set_topics(v);
        }
        if let Some(v) = version_aliases {
            model = model.set_version_aliases(v);
        }
        if let Some(v) = version_destroy_ttl {
            model = model.set_version_destroy_ttl(v);
        }
        model = model.set_labels(labels);

        self.secretmanager()
            .await?
            .update_secret()
            .set_secret(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_secret Secret", e))?;

        self.read_secretmanager_secret(provider_id).await
    }

    pub(super) async fn delete_secretmanager_secret(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.secretmanager()
            .await?
            .delete_secret()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteSecret", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn secretmanager_secret_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
