// Generated by smelt-codegen batch — do not edit by hand.
// Service: storage
// Resources: 1

use smelt_provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn storage_bucket_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "storage.Bucket".into(),
            description: "Bucket resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "labels".into(),
                                description: "Optional. User-provided labels, in key/value pairs.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "Identifier. The name of the bucket.".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "acl".into(),
                                description: "Optional. Access controls on the bucket.".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "autoclass".into(),
                                description: "Optional. The bucket's Autoclass configuration. If there is no".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "billing".into(),
                                description: "Optional. The bucket's billing configuration.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "cors".into(),
                                description: "Optional. The bucket's [CORS](https://www.w3.org/TR/cors/)".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "custom_placement_config".into(),
                                description: "Optional. Configuration that, if present, specifies the data placement for".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "default_event_based_hold".into(),
                                description: "Optional. The default value for event-based hold on newly created objects".into(),
                                field_type: smelt_provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "default_object_acl".into(),
                                description: "Optional. Default access controls to apply to new objects when no ACL is".into(),
                                field_type: smelt_provider::FieldType::Array(Box::new(smelt_provider::FieldType::Record(vec![]))),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "hierarchical_namespace".into(),
                                description: "Optional. The bucket's hierarchical namespace configuration. If there is no".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "iam_config".into(),
                                description: "Optional. The bucket's IAM configuration.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "ip_filter".into(),
                                description: "Optional. The bucket's IP filter configuration.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "location".into(),
                                description: "Immutable. The location of the bucket. Object data for objects in the".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "logging".into(),
                                description: "Optional. The bucket's logging config, which defines the destination bucket".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "object_retention".into(),
                                description: "Optional. The bucket's object retention configuration. Must be enabled".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "project".into(),
                                description: "Immutable. The project which owns this bucket, in the format of".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "retention_policy".into(),
                                description: "Optional. The bucket's retention policy. The retention policy enforces a".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "rpo".into(),
                                description: "Optional. The recovery point objective for cross-region replication of the".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "satisfies_pzs".into(),
                                description: "Optional. Reserved for future use.".into(),
                                field_type: smelt_provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "soft_delete_policy".into(),
                                description: "Optional. The bucket's soft delete policy. The soft delete policy prevents".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "storage_class".into(),
                                description: "Optional. The bucket's default storage class, used whenever no storageClass".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "website".into(),
                                description: "Optional. The bucket's website config, controlling how the service behaves".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "reliability".into(),
                        description: "Reliability configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "lifecycle".into(),
                                description: "Optional. The bucket's lifecycle configuration. See [Lifecycle".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "versioning".into(),
                                description: "Optional. The bucket's versioning configuration.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "encryption".into(),
                                description: "Optional. Encryption config for a bucket.".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_storage_bucket(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let acl = config.pointer("/config/acl").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::BucketAccessControl>>(
                v.clone(),
            )
            .ok()
        });
        let autoclass = config.pointer("/config/autoclass").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Autoclass>(v.clone()).ok()
        });
        let billing = config.pointer("/config/billing").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Billing>(v.clone()).ok()
        });
        let cors = config.pointer("/config/cors").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::bucket::Cors>>(v.clone()).ok()
        });
        let custom_placement_config =
            config
                .pointer("/config/custom_placement_config")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_storage::model::bucket::CustomPlacementConfig,
                    >(v.clone())
                    .ok()
                });
        let default_event_based_hold = config.optional_bool("/config/default_event_based_hold");
        let default_object_acl = config.pointer("/config/default_object_acl").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::ObjectAccessControl>>(
                v.clone(),
            )
            .ok()
        });
        let encryption = config.pointer("/security/encryption").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Encryption>(v.clone())
                .ok()
        });
        let hierarchical_namespace =
            config
                .pointer("/config/hierarchical_namespace")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_storage::model::bucket::HierarchicalNamespace,
                    >(v.clone())
                    .ok()
                });
        let iam_config = config.pointer("/config/iam_config").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::IamConfig>(v.clone()).ok()
        });
        let ip_filter = config.pointer("/config/ip_filter").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::IpFilter>(v.clone()).ok()
        });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let lifecycle = config.pointer("/reliability/lifecycle").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Lifecycle>(v.clone()).ok()
        });
        let location = config.optional_str("/config/location").map(String::from);
        let logging = config.pointer("/config/logging").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Logging>(v.clone()).ok()
        });
        let name = config.require_str("/identity/name")?.to_string();
        let object_retention = config.pointer("/config/object_retention").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::ObjectRetention>(
                v.clone(),
            )
            .ok()
        });
        let project = config.optional_str("/config/project").map(String::from);
        let retention_policy = config.pointer("/config/retention_policy").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::RetentionPolicy>(
                v.clone(),
            )
            .ok()
        });
        let rpo = config.optional_str("/config/rpo").map(String::from);
        let satisfies_pzs = config.optional_bool("/config/satisfies_pzs");
        let soft_delete_policy = config.pointer("/config/soft_delete_policy").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::SoftDeletePolicy>(
                v.clone(),
            )
            .ok()
        });
        let storage_class = config
            .optional_str("/config/storage_class")
            .map(String::from);
        let versioning = config.pointer("/reliability/versioning").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Versioning>(v.clone())
                .ok()
        });
        let website = config.pointer("/config/website").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Website>(v.clone()).ok()
        });

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_storage::model::Bucket::default();
        if let Some(v) = acl {
            model = model.set_acl(v);
        }
        if let Some(v) = autoclass {
            model = model.set_autoclass(v);
        }
        if let Some(v) = billing {
            model = model.set_billing(v);
        }
        if let Some(v) = cors {
            model = model.set_cors(v);
        }
        if let Some(v) = custom_placement_config {
            model = model.set_custom_placement_config(v);
        }
        if let Some(v) = default_event_based_hold {
            model = model.set_default_event_based_hold(v);
        }
        if let Some(v) = default_object_acl {
            model = model.set_default_object_acl(v);
        }
        if let Some(v) = encryption {
            model = model.set_encryption(v);
        }
        if let Some(v) = hierarchical_namespace {
            model = model.set_hierarchical_namespace(v);
        }
        if let Some(v) = iam_config {
            model = model.set_iam_config(v);
        }
        if let Some(v) = ip_filter {
            model = model.set_ip_filter(v);
        }
        if let Some(v) = lifecycle {
            model = model.set_lifecycle(v);
        }
        if let Some(v) = location {
            model = model.set_location(v);
        }
        if let Some(v) = logging {
            model = model.set_logging(v);
        }
        model = model.set_name(format!("projects/_/buckets/{name}"));
        if let Some(v) = object_retention {
            model = model.set_object_retention(v);
        }
        if let Some(v) = project {
            model = model.set_project(v);
        }
        if let Some(v) = retention_policy {
            model = model.set_retention_policy(v);
        }
        if let Some(v) = rpo {
            model = model.set_rpo(v);
        }
        if let Some(v) = satisfies_pzs {
            model = model.set_satisfies_pzs(v);
        }
        if let Some(v) = soft_delete_policy {
            model = model.set_soft_delete_policy(v);
        }
        if let Some(v) = storage_class {
            model = model.set_storage_class(v);
        }
        if let Some(v) = versioning {
            model = model.set_versioning(v);
        }
        if let Some(v) = website {
            model = model.set_website(v);
        }
        model = model.set_labels(labels);

        // Make API call — GCS requires projects/_ as parent (project inferred from auth)
        // Set project on the bucket model instead
        model = model.set_project(format!("projects/{}", self.project_id));
        self.storage()
            .await?
            .create_bucket()
            .set_parent("projects/_")
            .set_bucket_id(&name)
            .set_bucket(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_bucket Bucket", e))?;

        let provider_id = format!("projects/_/buckets/{}", name);
        self.read_storage_bucket(&provider_id).await
    }

    pub(super) async fn read_storage_bucket(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let bucket = self
            .storage()
            .await?
            .get_bucket()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetBucket", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = bucket
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        // Extract short bucket name from full resource path
        let short_name = provider_id.rsplit('/').next().unwrap_or(provider_id);

        let mut state = serde_json::json!({
            "identity": {
                "labels": user_labels,
                "name": short_name,
            },
            "config": {
                "location": bucket.location.as_str(),
                "storage_class": bucket.storage_class.as_str(),
            },
        });
        // Conditionally include optional config fields
        let rpo = bucket.rpo.as_str();
        if !rpo.is_empty() {
            state["config"]["rpo"] = serde_json::json!(rpo);
        }

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&bucket.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_storage_bucket(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let acl = config.pointer("/config/acl").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::BucketAccessControl>>(
                v.clone(),
            )
            .ok()
        });
        let autoclass = config.pointer("/config/autoclass").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Autoclass>(v.clone()).ok()
        });
        let billing = config.pointer("/config/billing").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Billing>(v.clone()).ok()
        });
        let cors = config.pointer("/config/cors").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::bucket::Cors>>(v.clone()).ok()
        });
        let custom_placement_config =
            config
                .pointer("/config/custom_placement_config")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_storage::model::bucket::CustomPlacementConfig,
                    >(v.clone())
                    .ok()
                });
        let default_event_based_hold = config.optional_bool("/config/default_event_based_hold");
        let default_object_acl = config.pointer("/config/default_object_acl").and_then(|v| {
            serde_json::from_value::<Vec<google_cloud_storage::model::ObjectAccessControl>>(
                v.clone(),
            )
            .ok()
        });
        let encryption = config.pointer("/security/encryption").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Encryption>(v.clone())
                .ok()
        });
        let hierarchical_namespace =
            config
                .pointer("/config/hierarchical_namespace")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_storage::model::bucket::HierarchicalNamespace,
                    >(v.clone())
                    .ok()
                });
        let iam_config = config.pointer("/config/iam_config").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::IamConfig>(v.clone()).ok()
        });
        let ip_filter = config.pointer("/config/ip_filter").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::IpFilter>(v.clone()).ok()
        });
        let lifecycle = config.pointer("/reliability/lifecycle").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Lifecycle>(v.clone()).ok()
        });
        let location = config.optional_str("/config/location").map(String::from);
        let logging = config.pointer("/config/logging").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Logging>(v.clone()).ok()
        });
        let object_retention = config.pointer("/config/object_retention").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::ObjectRetention>(
                v.clone(),
            )
            .ok()
        });
        let project = config.optional_str("/config/project").map(String::from);
        let retention_policy = config.pointer("/config/retention_policy").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::RetentionPolicy>(
                v.clone(),
            )
            .ok()
        });
        let rpo = config.optional_str("/config/rpo").map(String::from);
        let satisfies_pzs = config.optional_bool("/config/satisfies_pzs");
        let soft_delete_policy = config.pointer("/config/soft_delete_policy").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::SoftDeletePolicy>(
                v.clone(),
            )
            .ok()
        });
        let storage_class = config
            .optional_str("/config/storage_class")
            .map(String::from);
        let versioning = config.pointer("/reliability/versioning").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Versioning>(v.clone())
                .ok()
        });
        let website = config.pointer("/config/website").and_then(|v| {
            serde_json::from_value::<google_cloud_storage::model::bucket::Website>(v.clone()).ok()
        });
        let labels = super::extract_labels(config);

        let mut model = google_cloud_storage::model::Bucket::default();
        model = model.set_name(provider_id);
        if let Some(v) = acl {
            model = model.set_acl(v);
        }
        if let Some(v) = autoclass {
            model = model.set_autoclass(v);
        }
        if let Some(v) = billing {
            model = model.set_billing(v);
        }
        if let Some(v) = cors {
            model = model.set_cors(v);
        }
        if let Some(v) = custom_placement_config {
            model = model.set_custom_placement_config(v);
        }
        if let Some(v) = default_event_based_hold {
            model = model.set_default_event_based_hold(v);
        }
        if let Some(v) = default_object_acl {
            model = model.set_default_object_acl(v);
        }
        if let Some(v) = encryption {
            model = model.set_encryption(v);
        }
        if let Some(v) = hierarchical_namespace {
            model = model.set_hierarchical_namespace(v);
        }
        if let Some(v) = iam_config {
            model = model.set_iam_config(v);
        }
        if let Some(v) = ip_filter {
            model = model.set_ip_filter(v);
        }
        if let Some(v) = lifecycle {
            model = model.set_lifecycle(v);
        }
        if let Some(v) = location {
            model = model.set_location(v);
        }
        if let Some(v) = logging {
            model = model.set_logging(v);
        }
        if let Some(v) = object_retention {
            model = model.set_object_retention(v);
        }
        if let Some(v) = project {
            model = model.set_project(v);
        }
        if let Some(v) = retention_policy {
            model = model.set_retention_policy(v);
        }
        if let Some(v) = rpo {
            model = model.set_rpo(v);
        }
        if let Some(v) = satisfies_pzs {
            model = model.set_satisfies_pzs(v);
        }
        if let Some(v) = soft_delete_policy {
            model = model.set_soft_delete_policy(v);
        }
        if let Some(v) = storage_class {
            model = model.set_storage_class(v);
        }
        if let Some(v) = versioning {
            model = model.set_versioning(v);
        }
        if let Some(v) = website {
            model = model.set_website(v);
        }
        model = model.set_labels(labels);

        self.storage()
            .await?
            .update_bucket()
            .set_bucket(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_bucket Bucket", e))?;

        self.read_storage_bucket(provider_id).await
    }

    pub(super) async fn delete_storage_bucket(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.storage()
            .await?
            .delete_bucket()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteBucket", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn storage_bucket_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
