// Generated by smelt-codegen batch — do not edit by hand.
// Service: alloydb
// Resources: 3

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;
use google_cloud_lro::Poller;

impl GcpProvider {
    pub(super) fn alloydb_cluster_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "alloydb.Cluster".into(),
            description: "Cluster resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "display_name".into(),
                                description: "User-settable and human-readable display name for the Cluster.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels as key value pairs".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The name of the cluster resource with the format:".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "tags".into(),
                                description: "Optional. Input only. Immutable. Tag keys/values directly bound to this".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "annotations".into(),
                                description: "Annotations to allow client tools to store small amount of arbitrary data.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "automated_backup_policy".into(),
                                description: "The automated backup policy for this cluster.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "continuous_backup_config".into(),
                                description: "Optional. Continuous backup configuration for this cluster.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "database_version".into(),
                                description: "Optional. The database engine major version. This is an optional field and".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["DATABASE_VERSION_UNSPECIFIED".into(), "POSTGRES_13".into(), "POSTGRES_14".into(), "POSTGRES_15".into(), "POSTGRES_16".into(), "POSTGRES_17".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "encryption_config".into(),
                                description: "Optional. The encryption config can be specified to encrypt the data disks".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "initial_user".into(),
                                description: "Input only. Initial user to setup during cluster creation.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "maintenance_update_policy".into(),
                                description: "Optional. The maintenance update policy determines when to allow or deny".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "network_config".into(),
                                description: "".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "psc_config".into(),
                                description: "Optional. The configuration for Private Service Connect (PSC) for the".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "secondary_config".into(),
                                description: "Cross Region replication config specific to SECONDARY cluster.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "source".into(),
                                description: "In case of an imported cluster, this field contains information about the".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "subscription_type".into(),
                                description: "Optional. Subscription type of the cluster.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["SUBSCRIPTION_TYPE_UNSPECIFIED".into(), "STANDARD".into(), "TRIAL".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_alloydb_cluster(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let automated_backup_policy =
            config
                .pointer("/config/automated_backup_policy")
                .and_then(|v| {
                    serde_json::from_value::<google_cloud_alloydb_v1::model::AutomatedBackupPolicy>(
                        v.clone(),
                    )
                    .ok()
                });
        let continuous_backup_config = config.pointer("/config/continuous_backup_config").and_then(
            |v| {
                serde_json::from_value::<google_cloud_alloydb_v1::model::ContinuousBackupConfig>(
                    v.clone(),
                )
                .ok()
            },
        );
        let database_version = config
            .optional_str("/config/database_version")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let encryption_config = config.pointer("/config/encryption_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::EncryptionConfig>(v.clone())
                .ok()
        });
        let initial_user = config.pointer("/config/initial_user").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::UserPassword>(v.clone()).ok()
        });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let maintenance_update_policy = config
            .pointer("/config/maintenance_update_policy")
            .and_then(|v| {
                serde_json::from_value::<google_cloud_alloydb_v1::model::MaintenanceUpdatePolicy>(
                    v.clone(),
                )
                .ok()
            });
        let name = config.require_str("/identity/name")?.to_string();
        let network_config = config.pointer("/config/network_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::NetworkConfig>(
                v.clone(),
            )
            .ok()
        });
        let psc_config = config.pointer("/config/psc_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::PscConfig>(v.clone())
                .ok()
        });
        let secondary_config = config.pointer("/config/secondary_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::SecondaryConfig>(
                v.clone(),
            )
            .ok()
        });
        let subscription_type = config
            .optional_str("/config/subscription_type")
            .map(String::from);
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_alloydb_v1::model::Cluster::default();
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = automated_backup_policy {
            model = model.set_automated_backup_policy(v);
        }
        if let Some(v) = continuous_backup_config {
            model = model.set_continuous_backup_config(v);
        }
        if let Some(ref s) = database_version {
            model = model.set_database_version(
                google_cloud_alloydb_v1::model::DatabaseVersion::from(s.as_str()),
            );
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = encryption_config {
            model = model.set_encryption_config(v);
        }
        if let Some(v) = initial_user {
            model = model.set_initial_user(v);
        }
        if let Some(v) = maintenance_update_policy {
            model = model.set_maintenance_update_policy(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = network_config {
            model = model.set_network_config(v);
        }
        if let Some(v) = psc_config {
            model = model.set_psc_config(v);
        }
        if let Some(v) = secondary_config {
            model = model.set_secondary_config(v);
        }
        if let Some(v) = config.pointer("/config/cloudsql_backup_run_source") {
            let parsed: google_cloud_alloydb_v1::model::CloudSQLBackupRunSource =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("cloudsql_backup_run_source: {e}"))
                })?;
            model = model.set_cloudsql_backup_run_source(parsed);
        }
        if let Some(ref s) = subscription_type {
            model = model.set_subscription_type(
                google_cloud_alloydb_v1::model::SubscriptionType::from(s.as_str()),
            );
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.alloy_db_admin()
            .await?
            .create_cluster()
            .set_parent(&parent)
            .set_cluster_id(&name)
            .set_cluster(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_cluster Cluster", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/clusters/{}",
            self.project_id, self.region, name
        );
        self.read_alloydb_cluster(&provider_id).await
    }

    pub(super) async fn read_alloydb_cluster(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let cluster = self
            .alloy_db_admin()
            .await?
            .get_cluster()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetCluster", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = cluster
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "display_name": cluster.display_name.as_str(),
                "labels": user_labels,
                "name": cluster.name.as_str(),
                "tags": &cluster.tags,
            },
            "config": {
                "annotations": &cluster.annotations,
                "automated_backup_policy": &cluster.automated_backup_policy,
                "continuous_backup_config": &cluster.continuous_backup_config,
                "database_version": &cluster.database_version,
                "encryption_config": &cluster.encryption_config,
                "initial_user": &cluster.initial_user,
                "maintenance_update_policy": &cluster.maintenance_update_policy,
                "network_config": &cluster.network_config,
                "psc_config": &cluster.psc_config,
                "secondary_config": &cluster.secondary_config,
                "source": serde_json::Value::Null,
                "subscription_type": &cluster.subscription_type,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&cluster.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_alloydb_cluster(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let automated_backup_policy =
            config
                .pointer("/config/automated_backup_policy")
                .and_then(|v| {
                    serde_json::from_value::<google_cloud_alloydb_v1::model::AutomatedBackupPolicy>(
                        v.clone(),
                    )
                    .ok()
                });
        let continuous_backup_config = config.pointer("/config/continuous_backup_config").and_then(
            |v| {
                serde_json::from_value::<google_cloud_alloydb_v1::model::ContinuousBackupConfig>(
                    v.clone(),
                )
                .ok()
            },
        );
        let database_version = config
            .optional_str("/config/database_version")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let encryption_config = config.pointer("/config/encryption_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::EncryptionConfig>(v.clone())
                .ok()
        });
        let initial_user = config.pointer("/config/initial_user").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::UserPassword>(v.clone()).ok()
        });
        let maintenance_update_policy = config
            .pointer("/config/maintenance_update_policy")
            .and_then(|v| {
                serde_json::from_value::<google_cloud_alloydb_v1::model::MaintenanceUpdatePolicy>(
                    v.clone(),
                )
                .ok()
            });
        let network_config = config.pointer("/config/network_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::NetworkConfig>(
                v.clone(),
            )
            .ok()
        });
        let psc_config = config.pointer("/config/psc_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::PscConfig>(v.clone())
                .ok()
        });
        let secondary_config = config.pointer("/config/secondary_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::cluster::SecondaryConfig>(
                v.clone(),
            )
            .ok()
        });
        let subscription_type = config
            .optional_str("/config/subscription_type")
            .map(String::from);
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let labels = super::extract_labels(config);

        let mut model = google_cloud_alloydb_v1::model::Cluster::default();
        model = model.set_name(provider_id);
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = automated_backup_policy {
            model = model.set_automated_backup_policy(v);
        }
        if let Some(v) = continuous_backup_config {
            model = model.set_continuous_backup_config(v);
        }
        if let Some(ref s) = database_version {
            model = model.set_database_version(
                google_cloud_alloydb_v1::model::DatabaseVersion::from(s.as_str()),
            );
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = encryption_config {
            model = model.set_encryption_config(v);
        }
        if let Some(v) = initial_user {
            model = model.set_initial_user(v);
        }
        if let Some(v) = maintenance_update_policy {
            model = model.set_maintenance_update_policy(v);
        }
        if let Some(v) = network_config {
            model = model.set_network_config(v);
        }
        if let Some(v) = psc_config {
            model = model.set_psc_config(v);
        }
        if let Some(v) = secondary_config {
            model = model.set_secondary_config(v);
        }
        if let Some(v) = config.pointer("/config/cloudsql_backup_run_source") {
            let parsed: google_cloud_alloydb_v1::model::CloudSQLBackupRunSource =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("cloudsql_backup_run_source: {e}"))
                })?;
            model = model.set_cloudsql_backup_run_source(parsed);
        }
        if let Some(ref s) = subscription_type {
            model = model.set_subscription_type(
                google_cloud_alloydb_v1::model::SubscriptionType::from(s.as_str()),
            );
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        model = model.set_labels(labels);

        self.alloy_db_admin()
            .await?
            .update_cluster()
            .set_cluster(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_cluster Cluster", e))?;

        self.read_alloydb_cluster(provider_id).await
    }

    pub(super) async fn delete_alloydb_cluster(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.alloy_db_admin()
            .await?
            .delete_cluster()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteCluster", e))?;
        Ok(())
    }

    pub(super) fn alloydb_backup_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "alloydb.Backup".into(),
            description: "Backup resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "User-provided description of the backup.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "display_name".into(),
                                description: "User-settable and human-readable display name for the Backup.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels as key value pairs".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The name of the backup resource with the format:".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "tags".into(),
                                description: "Optional. Input only. Immutable. Tag keys/values directly bound to this".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "annotations".into(),
                                description: "Annotations to allow client tools to store small amount of arbitrary data.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "cluster_name".into(),
                                description: "Required. The full resource name of the backup source cluster".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "encryption_config".into(),
                                description: "Optional. The encryption config can be specified to encrypt the".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "type".into(),
                                description: "The backup type, which suggests the trigger for the backup.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["TYPE_UNSPECIFIED".into(), "GOOGLE_DEFAULT_ENCRYPTION".into(), "CUSTOMER_MANAGED_ENCRYPTION".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_alloydb_backup(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let cluster_name = config
            .optional_str("/config/cluster_name")
            .map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let encryption_config = config.pointer("/config/encryption_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::EncryptionConfig>(v.clone())
                .ok()
        });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let type_val = config.optional_str("/config/type").map(String::from);

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_alloydb_v1::model::Backup::default();
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = cluster_name {
            model = model.set_cluster_name(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = encryption_config {
            model = model.set_encryption_config(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(ref s) = type_val {
            model = model.set_type(google_cloud_alloydb_v1::model::backup::Type::from(
                s.as_str(),
            ));
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.alloy_db_admin()
            .await?
            .create_backup()
            .set_parent(&parent)
            .set_backup_id(&name)
            .set_backup(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_backup Backup", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/backups/{}",
            self.project_id, self.region, name
        );
        self.read_alloydb_backup(&provider_id).await
    }

    pub(super) async fn read_alloydb_backup(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let backup = self
            .alloy_db_admin()
            .await?
            .get_backup()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetBackup", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = backup
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": backup.description.as_str(),
                "display_name": backup.display_name.as_str(),
                "labels": user_labels,
                "name": backup.name.as_str(),
                "tags": &backup.tags,
            },
            "config": {
                "annotations": &backup.annotations,
                "cluster_name": backup.cluster_name.as_str(),
                "encryption_config": &backup.encryption_config,
                "type": &backup.r#type,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&backup.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_alloydb_backup(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let cluster_name = config
            .optional_str("/config/cluster_name")
            .map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let encryption_config = config.pointer("/config/encryption_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::EncryptionConfig>(v.clone())
                .ok()
        });
        let tags = config
            .pointer("/identity/tags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let type_val = config.optional_str("/config/type").map(String::from);
        let labels = super::extract_labels(config);

        let mut model = google_cloud_alloydb_v1::model::Backup::default();
        model = model.set_name(provider_id);
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(v) = cluster_name {
            model = model.set_cluster_name(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = encryption_config {
            model = model.set_encryption_config(v);
        }
        if let Some(v) = tags {
            model = model.set_tags(v);
        }
        if let Some(ref s) = type_val {
            model = model.set_type(google_cloud_alloydb_v1::model::backup::Type::from(
                s.as_str(),
            ));
        }
        model = model.set_labels(labels);

        self.alloy_db_admin()
            .await?
            .update_backup()
            .set_backup(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_backup Backup", e))?;

        self.read_alloydb_backup(provider_id).await
    }

    pub(super) async fn delete_alloydb_backup(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.alloy_db_admin()
            .await?
            .delete_backup()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteBackup", e))?;
        Ok(())
    }

    pub(super) fn alloydb_instance_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "alloydb.Instance".into(),
            description: "Instance resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "cluster_id".into(),
                                description: "Provider ID of the parent resource (injected via binding)".into(),
                                field_type: crate::provider::FieldType::Ref("*".into()),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "display_name".into(),
                                description: "User-settable and human-readable display name for the Instance.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels as key value pairs".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The name of the instance resource with the format:".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "activation_policy".into(),
                                description: "Optional. Specifies whether an instance needs to spin up. Once the instance".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["ACTIVATION_POLICY_UNSPECIFIED".into(), "ALWAYS".into(), "NEVER".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "annotations".into(),
                                description: "Annotations to allow client tools to store small amount of arbitrary data.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "availability_type".into(),
                                description: "Availability type of an Instance.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["AVAILABILITY_TYPE_UNSPECIFIED".into(), "ZONAL".into(), "REGIONAL".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "connection_pool_config".into(),
                                description: "Optional. The configuration for Managed Connection Pool (MCP).".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "database_flags".into(),
                                description: "Database flags. Set at the instance level.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "gce_zone".into(),
                                description: "The Compute Engine zone that the instance should serve from, per".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "machine_config".into(),
                                description: "Configurations for the machines that host the underlying".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "network_config".into(),
                                description: "Optional. Instance-level network configuration.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "psc_instance_config".into(),
                                description: "Optional. The configuration for Private Service Connect (PSC) for the".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "read_pool_config".into(),
                                description: "Read pool instance configuration.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "instance_type".into(),
                                description: "Required. The type of the instance. Specified at creation time.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["INSTANCE_TYPE_UNSPECIFIED".into(), "PRIMARY".into(), "READ_POOL".into(), "SECONDARY".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_alloydb_instance(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let activation_policy = config
            .optional_str("/config/activation_policy")
            .map(String::from);
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let availability_type = config
            .optional_str("/config/availability_type")
            .map(String::from);
        let connection_pool_config =
            config
                .pointer("/config/connection_pool_config")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_alloydb_v1::model::instance::ConnectionPoolConfig,
                    >(v.clone())
                    .ok()
                });
        let database_flags = config
            .pointer("/config/database_flags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let gce_zone = config.optional_str("/config/gce_zone").map(String::from);
        let instance_type = config
            .optional_str("/sizing/instance_type")
            .map(String::from);
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let machine_config = config.pointer("/config/machine_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::MachineConfig>(
                v.clone(),
            )
            .ok()
        });
        let name = config.require_str("/identity/name")?.to_string();
        let network_config = config.pointer("/config/network_config").and_then(|v| {
            serde_json::from_value::<
                    google_cloud_alloydb_v1::model::instance::InstanceNetworkConfig,
                >(v.clone())
                .ok()
        });
        let psc_instance_config = config.pointer("/config/psc_instance_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::PscInstanceConfig>(
                v.clone(),
            )
            .ok()
        });
        let read_pool_config = config.pointer("/config/read_pool_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::ReadPoolConfig>(
                v.clone(),
            )
            .ok()
        });

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_alloydb_v1::model::Instance::default();
        if let Some(ref s) = activation_policy {
            model = model.set_activation_policy(
                google_cloud_alloydb_v1::model::instance::ActivationPolicy::from(s.as_str()),
            );
        }
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(ref s) = availability_type {
            model = model.set_availability_type(
                google_cloud_alloydb_v1::model::instance::AvailabilityType::from(s.as_str()),
            );
        }
        if let Some(v) = connection_pool_config {
            model = model.set_connection_pool_config(v);
        }
        if let Some(v) = database_flags {
            model = model.set_database_flags(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = gce_zone {
            model = model.set_gce_zone(v);
        }
        if let Some(ref s) = instance_type {
            model = model.set_instance_type(
                google_cloud_alloydb_v1::model::instance::InstanceType::from(s.as_str()),
            );
        }
        if let Some(v) = machine_config {
            model = model.set_machine_config(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = network_config {
            model = model.set_network_config(v);
        }
        if let Some(v) = psc_instance_config {
            model = model.set_psc_instance_config(v);
        }
        if let Some(v) = read_pool_config {
            model = model.set_read_pool_config(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = config.require_str("/identity/cluster_id")?.to_string();
        self.alloy_db_admin()
            .await?
            .create_instance()
            .set_parent(&parent)
            .set_instance_id(&name)
            .set_instance(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_instance Instance", e))?;

        let provider_id = format!("{}/instances/{}", parent, name);
        self.read_alloydb_instance(&provider_id).await
    }

    pub(super) async fn read_alloydb_instance(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let instance = self
            .alloy_db_admin()
            .await?
            .get_instance()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetInstance", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = instance
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "display_name": instance.display_name.as_str(),
                "labels": user_labels,
                "name": instance.name.as_str(),
            },
            "config": {
                "activation_policy": &instance.activation_policy,
                "annotations": &instance.annotations,
                "availability_type": &instance.availability_type,
                "connection_pool_config": &instance.connection_pool_config,
                "database_flags": &instance.database_flags,
                "gce_zone": instance.gce_zone.as_str(),
                "machine_config": &instance.machine_config,
                "network_config": &instance.network_config,
                "psc_instance_config": &instance.psc_instance_config,
                "read_pool_config": &instance.read_pool_config,
            },
            "sizing": {
                "instance_type": &instance.instance_type,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&instance.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_alloydb_instance(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let activation_policy = config
            .optional_str("/config/activation_policy")
            .map(String::from);
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let availability_type = config
            .optional_str("/config/availability_type")
            .map(String::from);
        let connection_pool_config =
            config
                .pointer("/config/connection_pool_config")
                .and_then(|v| {
                    serde_json::from_value::<
                        google_cloud_alloydb_v1::model::instance::ConnectionPoolConfig,
                    >(v.clone())
                    .ok()
                });
        let database_flags = config
            .pointer("/config/database_flags")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let display_name = config
            .optional_str("/identity/display_name")
            .map(String::from);
        let gce_zone = config.optional_str("/config/gce_zone").map(String::from);
        let instance_type = config
            .optional_str("/sizing/instance_type")
            .map(String::from);
        let machine_config = config.pointer("/config/machine_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::MachineConfig>(
                v.clone(),
            )
            .ok()
        });
        let network_config = config.pointer("/config/network_config").and_then(|v| {
            serde_json::from_value::<
                    google_cloud_alloydb_v1::model::instance::InstanceNetworkConfig,
                >(v.clone())
                .ok()
        });
        let psc_instance_config = config.pointer("/config/psc_instance_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::PscInstanceConfig>(
                v.clone(),
            )
            .ok()
        });
        let read_pool_config = config.pointer("/config/read_pool_config").and_then(|v| {
            serde_json::from_value::<google_cloud_alloydb_v1::model::instance::ReadPoolConfig>(
                v.clone(),
            )
            .ok()
        });
        let labels = super::extract_labels(config);

        let mut model = google_cloud_alloydb_v1::model::Instance::default();
        model = model.set_name(provider_id);
        if let Some(ref s) = activation_policy {
            model = model.set_activation_policy(
                google_cloud_alloydb_v1::model::instance::ActivationPolicy::from(s.as_str()),
            );
        }
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        if let Some(ref s) = availability_type {
            model = model.set_availability_type(
                google_cloud_alloydb_v1::model::instance::AvailabilityType::from(s.as_str()),
            );
        }
        if let Some(v) = connection_pool_config {
            model = model.set_connection_pool_config(v);
        }
        if let Some(v) = database_flags {
            model = model.set_database_flags(v);
        }
        if let Some(v) = display_name {
            model = model.set_display_name(v);
        }
        if let Some(v) = gce_zone {
            model = model.set_gce_zone(v);
        }
        if let Some(ref s) = instance_type {
            model = model.set_instance_type(
                google_cloud_alloydb_v1::model::instance::InstanceType::from(s.as_str()),
            );
        }
        if let Some(v) = machine_config {
            model = model.set_machine_config(v);
        }
        if let Some(v) = network_config {
            model = model.set_network_config(v);
        }
        if let Some(v) = psc_instance_config {
            model = model.set_psc_instance_config(v);
        }
        if let Some(v) = read_pool_config {
            model = model.set_read_pool_config(v);
        }
        model = model.set_labels(labels);

        self.alloy_db_admin()
            .await?
            .update_instance()
            .set_instance(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_instance Instance", e))?;

        self.read_alloydb_instance(provider_id).await
    }

    pub(super) async fn delete_alloydb_instance(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.alloy_db_admin()
            .await?
            .delete_instance()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteInstance", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn alloydb_cluster_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn alloydb_backup_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn alloydb_instance_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
