// Generated by smelt-codegen batch — do not edit by hand.
// Service: artifactregistry
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;
use google_cloud_lro::Poller;

impl GcpProvider {
    pub(super) fn artifactregistry_repository_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "artifactregistry.Repository".into(),
            description: "Repository resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "The user-provided description of the repository.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels with user-defined metadata.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "The name of the repository, for example:".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "cleanup_policy_dry_run".into(),
                                description: "Optional. If true, the cleanup pipeline is prevented from deleting versions".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "disallow_unspecified_mode".into(),
                                description: "Optional. If this is true, an unspecified repo type will be treated as".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "format".into(),
                                description: "Optional. The format of packages that are stored in the repository.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["FORMAT_UNSPECIFIED".into(), "DOCKER".into(), "MAVEN".into(), "NPM".into(), "APT".into(), "YUM".into(), "PYTHON".into(), "KFP".into(), "GO".into(), "GENERIC".into(), "RUBY".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "format_config".into(),
                                description: "Repository-specific configurations.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "mode".into(),
                                description: "Optional. The mode of the repository.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["MODE_UNSPECIFIED".into(), "STANDARD_REPOSITORY".into(), "VIRTUAL_REPOSITORY".into(), "REMOTE_REPOSITORY".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "mode_config".into(),
                                description: "Repository configuration specific to the Mode value being selected (Remote".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "kms_key_name".into(),
                                description: "The Cloud KMS resource name of the customer managed encryption key that's".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_artifactregistry_repository(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let cleanup_policy_dry_run = config.optional_bool("/config/cleanup_policy_dry_run");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let disallow_unspecified_mode = config.optional_bool("/config/disallow_unspecified_mode");
        let format = config.optional_str("/config/format").map(String::from);
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let _labels = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let mode = config.optional_str("/config/mode").map(String::from);
        let name = config.require_str("/identity/name")?.to_string();

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_artifactregistry_v1::model::Repository::default();
        if let Some(v) = cleanup_policy_dry_run {
            model = model.set_cleanup_policy_dry_run(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = disallow_unspecified_mode {
            model = model.set_disallow_unspecified_mode(v);
        }
        if let Some(ref s) = format {
            model = model.set_format(
                google_cloud_artifactregistry_v1::model::repository::Format::from(s.as_str()),
            );
        }
        if let Some(v) = config.pointer("/config/maven_config") {
            let parsed: google_cloud_artifactregistry_v1::model::repository::MavenRepositoryConfig =
                serde_json::from_value(v.clone())
                    .map_err(|e| ProviderError::InvalidConfig(format!("maven_config: {e}")))?;
            model = model.set_maven_config(parsed);
        } else if let Some(v) = config.pointer("/config/docker_config") {
            let parsed: google_cloud_artifactregistry_v1::model::repository::DockerRepositoryConfig = serde_json::from_value(v.clone())
                .map_err(|e| ProviderError::InvalidConfig(format!("docker_config: {e}")))?;
            model = model.set_docker_config(parsed);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        if let Some(ref s) = mode {
            model = model.set_mode(
                google_cloud_artifactregistry_v1::model::repository::Mode::from(s.as_str()),
            );
        }
        if let Some(v) = config.pointer("/config/virtual_repository_config") {
            let parsed: google_cloud_artifactregistry_v1::model::VirtualRepositoryConfig =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("virtual_repository_config: {e}"))
                })?;
            model = model.set_virtual_repository_config(parsed);
        } else if let Some(v) = config.pointer("/config/remote_repository_config") {
            let parsed: google_cloud_artifactregistry_v1::model::RemoteRepositoryConfig =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("remote_repository_config: {e}"))
                })?;
            model = model.set_remote_repository_config(parsed);
        }
        model = model.set_name(name.clone());
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.artifact_registry()
            .await?
            .create_repository()
            .set_parent(&parent)
            .set_repository_id(&name)
            .set_repository(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_repository Repository", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/repositorys/{}",
            self.project_id, self.region, name
        );
        self.read_artifactregistry_repository(&provider_id).await
    }

    pub(super) async fn read_artifactregistry_repository(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let repository = self
            .artifact_registry()
            .await?
            .get_repository()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetRepository", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = repository
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": repository.description.as_str(),
                "labels": user_labels,
                "name": repository.name.as_str(),
            },
            "config": {
                "cleanup_policy_dry_run": repository.cleanup_policy_dry_run,
                "disallow_unspecified_mode": repository.disallow_unspecified_mode,
                "format": &repository.format,
                "format_config": serde_json::Value::Null,
                "mode": &repository.mode,
                "mode_config": serde_json::Value::Null,
            },
            "security": {
                "kms_key_name": repository.kms_key_name.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&repository.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_artifactregistry_repository(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let cleanup_policy_dry_run = config.optional_bool("/config/cleanup_policy_dry_run");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let disallow_unspecified_mode = config.optional_bool("/config/disallow_unspecified_mode");
        let format = config.optional_str("/config/format").map(String::from);
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let mode = config.optional_str("/config/mode").map(String::from);
        let labels = super::extract_labels(config);

        let mut model = google_cloud_artifactregistry_v1::model::Repository::default();
        model = model.set_name(provider_id);
        if let Some(v) = cleanup_policy_dry_run {
            model = model.set_cleanup_policy_dry_run(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = disallow_unspecified_mode {
            model = model.set_disallow_unspecified_mode(v);
        }
        if let Some(ref s) = format {
            model = model.set_format(
                google_cloud_artifactregistry_v1::model::repository::Format::from(s.as_str()),
            );
        }
        if let Some(v) = config.pointer("/config/maven_config") {
            let parsed: google_cloud_artifactregistry_v1::model::repository::MavenRepositoryConfig =
                serde_json::from_value(v.clone())
                    .map_err(|e| ProviderError::InvalidConfig(format!("maven_config: {e}")))?;
            model = model.set_maven_config(parsed);
        } else if let Some(v) = config.pointer("/config/docker_config") {
            let parsed: google_cloud_artifactregistry_v1::model::repository::DockerRepositoryConfig = serde_json::from_value(v.clone())
                .map_err(|e| ProviderError::InvalidConfig(format!("docker_config: {e}")))?;
            model = model.set_docker_config(parsed);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        if let Some(ref s) = mode {
            model = model.set_mode(
                google_cloud_artifactregistry_v1::model::repository::Mode::from(s.as_str()),
            );
        }
        if let Some(v) = config.pointer("/config/virtual_repository_config") {
            let parsed: google_cloud_artifactregistry_v1::model::VirtualRepositoryConfig =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("virtual_repository_config: {e}"))
                })?;
            model = model.set_virtual_repository_config(parsed);
        } else if let Some(v) = config.pointer("/config/remote_repository_config") {
            let parsed: google_cloud_artifactregistry_v1::model::RemoteRepositoryConfig =
                serde_json::from_value(v.clone()).map_err(|e| {
                    ProviderError::InvalidConfig(format!("remote_repository_config: {e}"))
                })?;
            model = model.set_remote_repository_config(parsed);
        }
        model = model.set_labels(labels);

        self.artifact_registry()
            .await?
            .update_repository()
            .set_repository(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_repository Repository", e))?;

        self.read_artifactregistry_repository(provider_id).await
    }

    pub(super) async fn delete_artifactregistry_repository(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.artifact_registry()
            .await?
            .delete_repository()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteRepository", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn artifactregistry_repository_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
