// Generated by smelt-codegen batch — do not edit by hand.
// Service: functions
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn functions_function_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "functions.Function".into(),
            description: "Function resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "User-provided description of a function.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels associated with this Cloud Function.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "A user-defined name of the function. Function names must be unique".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "build_config".into(),
                                description: "Describes the Build step of the function that builds a container from the".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "environment".into(),
                                description: "Describe whether the function is 1st Gen or 2nd Gen.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["ENVIRONMENT_UNSPECIFIED".into(), "GEN_1".into(), "GEN_2".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "event_trigger".into(),
                                description: "An Eventarc trigger managed by Google Cloud Functions that fires events in".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "service_config".into(),
                                description: "Describes the Service being deployed. Currently deploys services to Cloud".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "kms_key_name".into(),
                                description: "Resource name of a KMS crypto key (managed by the user) used to".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_functions_function(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let build_config = config.pointer("/config/build_config").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::BuildConfig>(v.clone()).ok()
        });
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let environment = config.optional_str("/config/environment").map(String::from);
        let event_trigger = config.pointer("/config/event_trigger").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::EventTrigger>(v.clone()).ok()
        });
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let service_config = config.pointer("/config/service_config").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::ServiceConfig>(v.clone())
                .ok()
        });

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_functions_v2::model::Function::default();
        if let Some(v) = build_config {
            model = model.set_build_config(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(ref s) = environment {
            model = model.set_environment(google_cloud_functions_v2::model::Environment::from(
                s.as_str(),
            ));
        }
        if let Some(v) = event_trigger {
            model = model.set_event_trigger(v);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        // Do NOT set model.name on create — name passed via set_function_id on request
        if let Some(v) = service_config {
            model = model.set_service_config(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.functions()
            .await?
            .create_function()
            .set_parent(&parent)
            .set_function_id(&name)
            .set_function(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_function Function", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/functions/{}",
            self.project_id, self.region, name
        );
        self.read_functions_function(&provider_id).await
    }

    pub(super) async fn read_functions_function(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let function = self
            .functions()
            .await?
            .get_function()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetFunction", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = function
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": function.description.as_str(),
                "labels": user_labels,
                "name": function.name.as_str(),
            },
            "config": {
                "build_config": &function.build_config,
                "environment": &function.environment,
                "event_trigger": &function.event_trigger,
                "service_config": &function.service_config,
            },
            "security": {
                "kms_key_name": function.kms_key_name.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&function.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_functions_function(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let build_config = config.pointer("/config/build_config").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::BuildConfig>(v.clone()).ok()
        });
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let environment = config.optional_str("/config/environment").map(String::from);
        let event_trigger = config.pointer("/config/event_trigger").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::EventTrigger>(v.clone()).ok()
        });
        let kms_key_name = config
            .optional_str("/security/kms_key_name")
            .map(String::from);
        let service_config = config.pointer("/config/service_config").and_then(|v| {
            serde_json::from_value::<google_cloud_functions_v2::model::ServiceConfig>(v.clone())
                .ok()
        });
        let labels = super::extract_labels(config);

        let mut model = google_cloud_functions_v2::model::Function::default();
        model = model.set_name(provider_id);
        if let Some(v) = build_config {
            model = model.set_build_config(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(ref s) = environment {
            model = model.set_environment(google_cloud_functions_v2::model::Environment::from(
                s.as_str(),
            ));
        }
        if let Some(v) = event_trigger {
            model = model.set_event_trigger(v);
        }
        if let Some(v) = kms_key_name {
            model = model.set_kms_key_name(v);
        }
        if let Some(v) = service_config {
            model = model.set_service_config(v);
        }
        model = model.set_labels(labels);

        self.functions()
            .await?
            .update_function()
            .set_function(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_function Function", e))?;

        self.read_functions_function(provider_id).await
    }

    pub(super) async fn delete_functions_function(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.functions()
            .await?
            .delete_function()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteFunction", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn functions_function_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
