// Generated by smelt-codegen batch — do not edit by hand.
// Service: gkebackup
// Resources: 2

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;
use google_cloud_lro::Poller;

impl GcpProvider {
    pub(super) fn gkebackup_backupplan_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "gkebackup.BackupPlan".into(),
            description: "BackupPlan resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Optional. User specified descriptive string for this BackupPlan.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Optional. A set of custom labels supplied by user.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The full name of the BackupPlan resource.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "backup_config".into(),
                                description: "Optional. Defines the configuration of Backups created via this BackupPlan.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "backup_schedule".into(),
                                description: "Optional. Defines a schedule for automatic Backup creation via this".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "cluster".into(),
                                description: "Required. Immutable. The source cluster from which Backups will be created".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "deactivated".into(),
                                description: "Optional. This flag indicates whether this BackupPlan has been deactivated.".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "retention_policy".into(),
                                description: "Optional. RetentionPolicy governs lifecycle of Backups created under this".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_gkebackup_backupplan(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let backup_config = config.pointer("/config/backup_config").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::backup_plan::BackupConfig>(
                v.clone(),
            )
            .ok()
        });
        let backup_schedule = config.pointer("/config/backup_schedule").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::backup_plan::Schedule>(
                v.clone(),
            )
            .ok()
        });
        let cluster = config.optional_str("/config/cluster").map(String::from);
        let deactivated = config.optional_bool("/config/deactivated");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let _labels = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let retention_policy = config.pointer("/config/retention_policy").and_then(|v| {
            serde_json::from_value::<
                    google_cloud_gkebackup_v1::model::backup_plan::RetentionPolicy,
                >(v.clone())
                .ok()
        });

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_gkebackup_v1::model::BackupPlan::default();
        if let Some(v) = backup_config {
            model = model.set_backup_config(v);
        }
        if let Some(v) = backup_schedule {
            model = model.set_backup_schedule(v);
        }
        if let Some(v) = cluster {
            model = model.set_cluster(v);
        }
        if let Some(v) = deactivated {
            model = model.set_deactivated(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = retention_policy {
            model = model.set_retention_policy(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.backup_for_gke()
            .await?
            .create_backup_plan()
            .set_parent(&parent)
            .set_backup_plan_id(&name)
            .set_backup_plan(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_backup_plan BackupPlan", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/backup_plans/{}",
            self.project_id, self.region, name
        );
        self.read_gkebackup_backupplan(&provider_id).await
    }

    pub(super) async fn read_gkebackup_backupplan(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let backup_plan = self
            .backup_for_gke()
            .await?
            .get_backup_plan()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetBackupPlan", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = backup_plan
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": backup_plan.description.as_str(),
                "labels": user_labels,
                "name": backup_plan.name.as_str(),
            },
            "config": {
                "backup_config": &backup_plan.backup_config,
                "backup_schedule": &backup_plan.backup_schedule,
                "cluster": backup_plan.cluster.as_str(),
                "deactivated": backup_plan.deactivated,
                "retention_policy": &backup_plan.retention_policy,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&backup_plan.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_gkebackup_backupplan(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let backup_config = config.pointer("/config/backup_config").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::backup_plan::BackupConfig>(
                v.clone(),
            )
            .ok()
        });
        let backup_schedule = config.pointer("/config/backup_schedule").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::backup_plan::Schedule>(
                v.clone(),
            )
            .ok()
        });
        let cluster = config.optional_str("/config/cluster").map(String::from);
        let deactivated = config.optional_bool("/config/deactivated");
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let retention_policy = config.pointer("/config/retention_policy").and_then(|v| {
            serde_json::from_value::<
                    google_cloud_gkebackup_v1::model::backup_plan::RetentionPolicy,
                >(v.clone())
                .ok()
        });
        let labels = super::extract_labels(config);

        let mut model = google_cloud_gkebackup_v1::model::BackupPlan::default();
        model = model.set_name(provider_id);
        if let Some(v) = backup_config {
            model = model.set_backup_config(v);
        }
        if let Some(v) = backup_schedule {
            model = model.set_backup_schedule(v);
        }
        if let Some(v) = cluster {
            model = model.set_cluster(v);
        }
        if let Some(v) = deactivated {
            model = model.set_deactivated(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = retention_policy {
            model = model.set_retention_policy(v);
        }
        model = model.set_labels(labels);

        self.backup_for_gke()
            .await?
            .update_backup_plan()
            .set_backup_plan(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_backup_plan BackupPlan", e))?;

        self.read_gkebackup_backupplan(provider_id).await
    }

    pub(super) async fn delete_gkebackup_backupplan(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.backup_for_gke()
            .await?
            .delete_backup_plan()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteBackupPlan", e))?;
        Ok(())
    }

    pub(super) fn gkebackup_restoreplan_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "gkebackup.RestorePlan".into(),
            description: "RestorePlan resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Optional. User specified descriptive string for this RestorePlan.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Optional. A set of custom labels supplied by user.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The full name of the RestorePlan resource.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "backup_plan".into(),
                                description: "Required. Immutable. A reference to the".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "cluster".into(),
                                description: "Required. Immutable. The target cluster into which Restores created via".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "restore_config".into(),
                                description: "Required. Configuration of Restores created via this RestorePlan.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_gkebackup_restoreplan(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let backup_plan = config.optional_str("/config/backup_plan").map(String::from);
        let cluster = config.optional_str("/config/cluster").map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let _labels = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let restore_config = config.pointer("/config/restore_config").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::RestoreConfig>(v.clone())
                .ok()
        });

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_gkebackup_v1::model::RestorePlan::default();
        if let Some(v) = backup_plan {
            model = model.set_backup_plan(v);
        }
        if let Some(v) = cluster {
            model = model.set_cluster(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = restore_config {
            model = model.set_restore_config(v);
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.backup_for_gke()
            .await?
            .create_restore_plan()
            .set_parent(&parent)
            .set_restore_plan_id(&name)
            .set_restore_plan(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_restore_plan RestorePlan", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/restore_plans/{}",
            self.project_id, self.region, name
        );
        self.read_gkebackup_restoreplan(&provider_id).await
    }

    pub(super) async fn read_gkebackup_restoreplan(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let restore_plan = self
            .backup_for_gke()
            .await?
            .get_restore_plan()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetRestorePlan", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = restore_plan
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "description": restore_plan.description.as_str(),
                "labels": user_labels,
                "name": restore_plan.name.as_str(),
            },
            "config": {
                "backup_plan": restore_plan.backup_plan.as_str(),
                "cluster": restore_plan.cluster.as_str(),
                "restore_config": &restore_plan.restore_config,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&restore_plan.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_gkebackup_restoreplan(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let backup_plan = config.optional_str("/config/backup_plan").map(String::from);
        let cluster = config.optional_str("/config/cluster").map(String::from);
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let restore_config = config.pointer("/config/restore_config").and_then(|v| {
            serde_json::from_value::<google_cloud_gkebackup_v1::model::RestoreConfig>(v.clone())
                .ok()
        });
        let labels = super::extract_labels(config);

        let mut model = google_cloud_gkebackup_v1::model::RestorePlan::default();
        model = model.set_name(provider_id);
        if let Some(v) = backup_plan {
            model = model.set_backup_plan(v);
        }
        if let Some(v) = cluster {
            model = model.set_cluster(v);
        }
        if let Some(v) = description {
            model = model.set_description(v);
        }
        if let Some(v) = restore_config {
            model = model.set_restore_config(v);
        }
        model = model.set_labels(labels);

        self.backup_for_gke()
            .await?
            .update_restore_plan()
            .set_restore_plan(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_restore_plan RestorePlan", e))?;

        self.read_gkebackup_restoreplan(provider_id).await
    }

    pub(super) async fn delete_gkebackup_restoreplan(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.backup_for_gke()
            .await?
            .delete_restore_plan()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteRestorePlan", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn gkebackup_backupplan_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn gkebackup_restoreplan_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
