// Generated by smelt-codegen batch — do not edit by hand.
// Service: kms
// Resources: 2

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn kms_keyring_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "kms.KeyRing".into(),
            description: "KeyRing resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![crate::provider::SectionSchema {
                    name: "identity".into(),
                    description: "Identity configuration".into(),
                    fields: vec![crate::provider::FieldSchema {
                        name: "name".into(),
                        description: "Output only. The resource name for the".into(),
                        field_type: crate::provider::FieldType::String,
                        required: true,
                        default: None,
                        sensitive: false,
                    }],
                }],
            },
        }
    }

    pub(super) async fn create_kms_keyring(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let name = config.require_str("/identity/name")?.to_string();

        // Build SDK model
        let mut model = google_cloud_kms_v1::model::KeyRing::default();
        model = model.set_name(name.clone());

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.kms()
            .await?
            .create_key_ring()
            .set_parent(&parent)
            .set_key_ring_id(&name)
            .set_key_ring(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_key_ring KeyRing", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/key_rings/{}",
            self.project_id, self.region, name
        );
        self.read_kms_keyring(&provider_id).await
    }

    pub(super) async fn read_kms_keyring(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let key_ring = self
            .kms()
            .await?
            .get_key_ring()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetKeyRing", e))?;

        let state = serde_json::json!({
            "identity": {
                "name": key_ring.name.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&key_ring.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_kms_keyring(
        &self,
        _provider_id: &str,
        _config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        Err(ProviderError::RequiresReplacement(
            "resource does not support in-place update".into(),
        ))
    }

    pub(super) async fn delete_kms_keyring(&self, _provider_id: &str) -> Result<(), ProviderError> {
        Err(ProviderError::ApiError(
            "delete not supported for this resource type".into(),
        ))
    }

    pub(super) fn kms_cryptokey_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "kms.CryptoKey".into(),
            description: "CryptoKey resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Labels with user-defined metadata. For more information, see".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The resource name for this".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "crypto_key_backend".into(),
                                description: "Immutable. The resource name of the backend environment where the key".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "destroy_scheduled_duration".into(),
                                description: "Immutable. The period of time that versions of this key spend in the".into(),
                                field_type: crate::provider::FieldType::String /* Duration */,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "import_only".into(),
                                description: "Immutable. Whether this key may contain imported versions only.".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "next_rotation_time".into(),
                                description: "At [next_rotation_time][google.cloud.kms.v1.CryptoKey.next_rotation_time],".into(),
                                field_type: crate::provider::FieldType::String /* Timestamp */,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "purpose".into(),
                                description: "Immutable. The immutable purpose of this".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["CRYPTO_KEY_PURPOSE_UNSPECIFIED".into(), "ENCRYPT_DECRYPT".into(), "ASYMMETRIC_SIGN".into(), "ASYMMETRIC_DECRYPT".into(), "RAW_ENCRYPT_DECRYPT".into(), "MAC".into(), "KEY_ENCAPSULATION".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "rotation_schedule".into(),
                                description: "Controls the rate of automatic rotation.".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["TODO: list variants for RotationSchedule".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "version_template".into(),
                                description: "A template describing settings for new".into(),
                                field_type: crate::provider::FieldType::String /* Nested(CryptoKeyVersionTemplate) */,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_kms_cryptokey(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let crypto_key_backend = config
            .optional_str("/config/crypto_key_backend")
            .map(String::from);
        // TODO: extract destroy_scheduled_duration (Duration) from config["/config/destroy_scheduled_duration"]
        let import_only = config.optional_bool("/config/import_only");
        // TODO: extract labels (Record) from config["/identity/labels"]
        let name = config.require_str("/identity/name")?.to_string();
        // TODO: extract next_rotation_time (Timestamp) from config["/config/next_rotation_time"]
        // TODO: extract purpose (Enum(CryptoKeyPurpose)) from config["/config/purpose"]
        // TODO: extract rotation_schedule (Enum(RotationSchedule)) from config["/config/rotation_schedule"]
        // TODO: extract version_template (Nested(CryptoKeyVersionTemplate)) from config["/config/version_template"]

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_kms_v1::model::CryptoKey::default();
        if let Some(v) = crypto_key_backend {
            model = model.set_crypto_key_backend(v);
        }
        // TODO: set destroy_scheduled_duration on model via .set_destroy_scheduled_duration()
        if let Some(v) = import_only {
            model = model.set_import_only(v);
        }
        model = model.set_name(name.clone());
        // TODO: set next_rotation_time on model via .set_next_rotation_time()
        // TODO: set purpose on model via .set_purpose()
        // TODO: set rotation_schedule on model via .set_rotation_schedule()
        // TODO: set version_template on model via .set_version_template()
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.kms()
            .await?
            .create_crypto_key()
            .set_parent(&parent)
            .set_crypto_key_id(&name)
            .set_crypto_key(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_crypto_key CryptoKey", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/crypto_keys/{}",
            self.project_id, self.region, name
        );
        self.read_kms_cryptokey(&provider_id).await
    }

    pub(super) async fn read_kms_cryptokey(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let crypto_key = self
            .kms()
            .await?
            .get_crypto_key()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetCryptoKey", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = crypto_key
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "labels": user_labels,
                "name": crypto_key.name.as_str(),
            },
            "config": {
                "crypto_key_backend": crypto_key.crypto_key_backend.as_str(),
                "destroy_scheduled_duration": serde_json::Value::Null /* TODO: destroy_scheduled_duration is complex type */,
                "import_only": crypto_key.import_only,
                "next_rotation_time": serde_json::Value::Null /* TODO: next_rotation_time is complex type */,
                "purpose": serde_json::Value::Null /* TODO: purpose is complex type */,
                "rotation_schedule": serde_json::Value::Null /* TODO: rotation_schedule is complex type */,
                "version_template": serde_json::Value::Null /* TODO: version_template is complex type */,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&crypto_key.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_kms_cryptokey(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let crypto_key_backend = config
            .optional_str("/config/crypto_key_backend")
            .map(String::from);
        // TODO: extract destroy_scheduled_duration (Duration) from config["/config/destroy_scheduled_duration"]
        let import_only = config.optional_bool("/config/import_only");
        // TODO: extract next_rotation_time (Timestamp) from config["/config/next_rotation_time"]
        // TODO: extract purpose (Enum(CryptoKeyPurpose)) from config["/config/purpose"]
        // TODO: extract rotation_schedule (Enum(RotationSchedule)) from config["/config/rotation_schedule"]
        // TODO: extract version_template (Nested(CryptoKeyVersionTemplate)) from config["/config/version_template"]
        let labels = super::extract_labels(config);

        let mut model = google_cloud_kms_v1::model::CryptoKey::default();
        model = model.set_name(provider_id);
        if let Some(v) = crypto_key_backend {
            model = model.set_crypto_key_backend(v);
        }
        // TODO: set destroy_scheduled_duration on model via .set_destroy_scheduled_duration()
        if let Some(v) = import_only {
            model = model.set_import_only(v);
        }
        // TODO: set next_rotation_time on model via .set_next_rotation_time()
        // TODO: set purpose on model via .set_purpose()
        // TODO: set rotation_schedule on model via .set_rotation_schedule()
        // TODO: set version_template on model via .set_version_template()
        model = model.set_labels(labels);

        self.kms()
            .await?
            .update_crypto_key()
            .set_crypto_key(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_crypto_key CryptoKey", e))?;

        self.read_kms_cryptokey(provider_id).await
    }

    pub(super) async fn delete_kms_cryptokey(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.kms()
            .await?
            .destroy_crypto_key_version()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteCryptoKey", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn kms_keyring_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn kms_cryptokey_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
