// Generated by smelt-codegen batch — do not edit by hand.
// Service: logging
// Resources: 1

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn logging_logbucket_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "logging.LogBucket".into(),
            description: "LogBucket resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "description".into(),
                                description: "Describes this bucket.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Output only. The resource name of the bucket.".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "analytics_enabled".into(),
                                description: "Whether log analytics is enabled for this bucket.".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "cmek_settings".into(),
                                description: "The CMEK settings of the log bucket. If present, new log entries written to".into(),
                                field_type: crate::provider::FieldType::String /* Nested(CmekSettings) */,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "index_configs".into(),
                                description: "A list of indexed fields and related configuration data.".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(crate::provider::FieldType::String /* Nested(IndexConfig) */)),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "locked".into(),
                                description: "Whether the bucket is locked.".into(),
                                field_type: crate::provider::FieldType::Bool,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "restricted_fields".into(),
                                description: "Log entry field paths that are denied access in this bucket.".into(),
                                field_type: crate::provider::FieldType::Array(Box::new(crate::provider::FieldType::String)),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "retention_days".into(),
                                description: "Logs will be retained by default for this amount of time, after which they".into(),
                                field_type: crate::provider::FieldType::Integer,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_logging_logbucket(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let analytics_enabled = config.optional_bool("/config/analytics_enabled");
        // TODO: extract cmek_settings (Nested(CmekSettings)) from config["/config/cmek_settings"]
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        // TODO: extract index_configs (Array(Nested(IndexConfig))) from config["/config/index_configs"]
        let locked = config.optional_bool("/config/locked");
        let name = config.require_str("/identity/name")?.to_string();
        // TODO: extract restricted_fields (Array(String)) from config["/config/restricted_fields"]
        let retention_days = config.optional_i64("/config/retention_days");

        // Build SDK model
        let mut model = google_cloud_logging_v2::model::LogBucket::default();
        if let Some(v) = analytics_enabled {
            model = model.set_analytics_enabled(v);
        }
        // TODO: set cmek_settings on model via .set_cmek_settings()
        if let Some(v) = description {
            model = model.set_description(v);
        }
        // TODO: set index_configs on model via .set_index_configs()
        if let Some(v) = locked {
            model = model.set_locked(v);
        }
        model = model.set_name(name.clone());
        // TODO: set restricted_fields on model via .set_restricted_fields()
        if let Some(v) = retention_days {
            model = model.set_retention_days(v as i32);
        }

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.logging()
            .await?
            .create_bucket()
            .set_parent(&parent)
            .set_bucket_id(&name)
            .set_bucket(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_bucket LogBucket", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/log_buckets/{}",
            self.project_id, self.region, name
        );
        self.read_logging_logbucket(&provider_id).await
    }

    pub(super) async fn read_logging_logbucket(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let log_bucket = self
            .logging()
            .await?
            .get_bucket()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetLogBucket", e))?;

        let state = serde_json::json!({
            "identity": {
                "description": log_bucket.description.as_str(),
                "name": log_bucket.name.as_str(),
            },
            "config": {
                "analytics_enabled": log_bucket.analytics_enabled,
                "cmek_settings": serde_json::Value::Null /* TODO: cmek_settings is complex type */,
                "index_configs": serde_json::Value::Null /* TODO: index_configs is complex type */,
                "locked": log_bucket.locked,
                "restricted_fields": serde_json::Value::Null /* TODO: restricted_fields is complex type */,
                "retention_days": log_bucket.retention_days,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&log_bucket.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_logging_logbucket(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let analytics_enabled = config.optional_bool("/config/analytics_enabled");
        // TODO: extract cmek_settings (Nested(CmekSettings)) from config["/config/cmek_settings"]
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        // TODO: extract index_configs (Array(Nested(IndexConfig))) from config["/config/index_configs"]
        let locked = config.optional_bool("/config/locked");
        // TODO: extract restricted_fields (Array(String)) from config["/config/restricted_fields"]
        let retention_days = config.optional_i64("/config/retention_days");

        let mut model = google_cloud_logging_v2::model::LogBucket::default();
        model = model.set_name(provider_id);
        if let Some(v) = analytics_enabled {
            model = model.set_analytics_enabled(v);
        }
        // TODO: set cmek_settings on model via .set_cmek_settings()
        if let Some(v) = description {
            model = model.set_description(v);
        }
        // TODO: set index_configs on model via .set_index_configs()
        if let Some(v) = locked {
            model = model.set_locked(v);
        }
        // TODO: set restricted_fields on model via .set_restricted_fields()
        if let Some(v) = retention_days {
            model = model.set_retention_days(v as i32);
        }

        self.logging()
            .await?
            .update_bucket()
            .set_bucket(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_bucket LogBucket", e))?;

        self.read_logging_logbucket(provider_id).await
    }

    pub(super) async fn delete_logging_logbucket(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.logging()
            .await?
            .delete_bucket()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteLogBucket", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn logging_logbucket_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
