// Generated by smelt-codegen batch — do not edit by hand.
// Service: privateca
// Resources: 2

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;
use google_cloud_lro::Poller;

impl GcpProvider {
    pub(super) fn privateca_capool_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "privateca.CaPool".into(),
            description: "CaPool resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Optional. Labels with user-defined metadata.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Identifier. The resource name for this".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "issuance_policy".into(),
                                description: "Optional. The".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "publishing_options".into(),
                                description: "Optional. The".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "tier".into(),
                                description: "Required. Immutable. The".into(),
                                field_type: crate::provider::FieldType::Enum(vec![
                                    "TIER_UNSPECIFIED".into(),
                                    "ENTERPRISE".into(),
                                    "DEVOPS".into(),
                                ]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_privateca_capool(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let issuance_policy = config.pointer("/config/issuance_policy").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::ca_pool::IssuancePolicy,
            >(v.clone())
            .ok()
        });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let publishing_options = config.pointer("/config/publishing_options").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::ca_pool::PublishingOptions,
            >(v.clone())
            .ok()
        });
        let tier = config.optional_str("/config/tier").map(String::from);

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_security_privateca_v1::model::CaPool::default();
        if let Some(v) = issuance_policy {
            model = model.set_issuance_policy(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = publishing_options {
            model = model.set_publishing_options(v);
        }
        if let Some(ref s) = tier {
            model = model.set_tier(
                google_cloud_security_privateca_v1::model::ca_pool::Tier::from(s.as_str()),
            );
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.certificate_authority_service()
            .await?
            .create_ca_pool()
            .set_parent(&parent)
            .set_ca_pool_id(&name)
            .set_ca_pool(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("Create_ca_pool CaPool", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/caPools/{}",
            self.project_id, self.region, name
        );
        self.read_privateca_capool(&provider_id).await
    }

    pub(super) async fn read_privateca_capool(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let ca_pool = self
            .certificate_authority_service()
            .await?
            .get_ca_pool()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetCaPool", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = ca_pool
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "labels": user_labels,
                "name": ca_pool.name.as_str(),
            },
            "config": {
                "issuance_policy": &ca_pool.issuance_policy,
                "publishing_options": &ca_pool.publishing_options,
                "tier": &ca_pool.tier,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&ca_pool.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_privateca_capool(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let issuance_policy = config.pointer("/config/issuance_policy").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::ca_pool::IssuancePolicy,
            >(v.clone())
            .ok()
        });
        let publishing_options = config.pointer("/config/publishing_options").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::ca_pool::PublishingOptions,
            >(v.clone())
            .ok()
        });
        let tier = config.optional_str("/config/tier").map(String::from);
        let labels = super::extract_labels(config);

        let mut model = google_cloud_security_privateca_v1::model::CaPool::default();
        model = model.set_name(provider_id);
        if let Some(v) = issuance_policy {
            model = model.set_issuance_policy(v);
        }
        if let Some(v) = publishing_options {
            model = model.set_publishing_options(v);
        }
        if let Some(ref s) = tier {
            model = model.set_tier(
                google_cloud_security_privateca_v1::model::ca_pool::Tier::from(s.as_str()),
            );
        }
        model = model.set_labels(labels);

        self.certificate_authority_service()
            .await?
            .update_ca_pool()
            .set_ca_pool(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("update_ca_pool CaPool", e))?;

        self.read_privateca_capool(provider_id).await
    }

    pub(super) async fn delete_privateca_capool(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.certificate_authority_service()
            .await?
            .delete_ca_pool()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteCaPool", e))?;
        Ok(())
    }

    pub(super) fn privateca_certificateauthority_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "privateca.CertificateAuthority".into(),
            description: "CertificateAuthority resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "ca_pool_id".into(),
                                description: "Provider ID of the parent resource (injected via binding)".into(),
                                field_type: crate::provider::FieldType::Ref("*".into()),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "labels".into(),
                                description: "Optional. Labels with user-defined metadata.".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Identifier. The resource name for this".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "config".into(),
                                description: "Required. Immutable. The config used to create a self-signed X.509".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "gcs_bucket".into(),
                                description: "Immutable. The name of a Cloud Storage bucket where this".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "key_spec".into(),
                                description: "Required. Immutable. Used when issuing certificates for this".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "lifetime".into(),
                                description: "Required. Immutable. The desired lifetime of the CA certificate. Used to".into(),
                                field_type: crate::provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "subordinate_config".into(),
                                description: "Optional. If this is a subordinate".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "type".into(),
                                description: "Required. Immutable. The".into(),
                                field_type: crate::provider::FieldType::Enum(vec!["TYPE_UNSPECIFIED".into(), "SELF_SIGNED".into(), "SUBORDINATE".into()]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_privateca_certificateauthority(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let config_val = config.pointer("/config/config").and_then(|v| {
            serde_json::from_value::<google_cloud_security_privateca_v1::model::CertificateConfig>(
                v.clone(),
            )
            .ok()
        });
        let gcs_bucket = config.optional_str("/config/gcs_bucket").map(String::from);
        let key_spec = config.pointer("/config/key_spec").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::certificate_authority::KeyVersionSpec,
            >(v.clone())
            .ok()
        });
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let lifetime = config
            .pointer("/config/lifetime")
            .and_then(|v| serde_json::from_value::<google_cloud_wkt::Duration>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();
        let subordinate_config = config.pointer("/config/subordinate_config").and_then(|v| {
            serde_json::from_value::<google_cloud_security_privateca_v1::model::SubordinateConfig>(
                v.clone(),
            )
            .ok()
        });
        let type_val = config.optional_str("/config/type").map(String::from);

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_security_privateca_v1::model::CertificateAuthority::default();
        if let Some(v) = config_val {
            model = model.set_config(v);
        }
        if let Some(v) = gcs_bucket {
            model = model.set_gcs_bucket(v);
        }
        if let Some(v) = key_spec {
            model = model.set_key_spec(v);
        }
        if let Some(v) = lifetime {
            model = model.set_lifetime(v);
        }
        model = model.set_name(name.clone());
        if let Some(v) = subordinate_config {
            model = model.set_subordinate_config(v);
        }
        if let Some(ref s) = type_val {
            model = model.set_type(
                google_cloud_security_privateca_v1::model::certificate_authority::Type::from(
                    s.as_str(),
                ),
            );
        }
        model = model.set_labels(labels);

        // Make API call
        let parent = config.require_str("/identity/ca_pool_id")?.to_string();
        self.certificate_authority_service()
            .await?
            .create_certificate_authority()
            .set_parent(&parent)
            .set_certificate_authority_id(&name)
            .set_certificate_authority(model)
            .poller()
            .until_done()
            .await
            .map_err(|e| {
                super::classify_gcp_error("Create_certificate_authority CertificateAuthority", e)
            })?;

        let provider_id = format!("{}/certificateAuthorities/{}", parent, name);
        self.read_privateca_certificateauthority(&provider_id).await
    }

    pub(super) async fn read_privateca_certificateauthority(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let certificate_authority = self
            .certificate_authority_service()
            .await?
            .get_certificate_authority()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetCertificateAuthority", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = certificate_authority
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "labels": user_labels,
                "name": certificate_authority.name.as_str(),
            },
            "config": {
                "config": &certificate_authority.config,
                "gcs_bucket": certificate_authority.gcs_bucket.as_str(),
                "key_spec": &certificate_authority.key_spec,
                "lifetime": &certificate_authority.lifetime,
                "subordinate_config": &certificate_authority.subordinate_config,
                "type": &certificate_authority.r#type,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "name".into(),
            serde_json::json!(&certificate_authority.name),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_privateca_certificateauthority(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let config_val = config.pointer("/config/config").and_then(|v| {
            serde_json::from_value::<google_cloud_security_privateca_v1::model::CertificateConfig>(
                v.clone(),
            )
            .ok()
        });
        let gcs_bucket = config.optional_str("/config/gcs_bucket").map(String::from);
        let key_spec = config.pointer("/config/key_spec").and_then(|v| {
            serde_json::from_value::<
                google_cloud_security_privateca_v1::model::certificate_authority::KeyVersionSpec,
            >(v.clone())
            .ok()
        });
        let lifetime = config
            .pointer("/config/lifetime")
            .and_then(|v| serde_json::from_value::<google_cloud_wkt::Duration>(v.clone()).ok());
        let subordinate_config = config.pointer("/config/subordinate_config").and_then(|v| {
            serde_json::from_value::<google_cloud_security_privateca_v1::model::SubordinateConfig>(
                v.clone(),
            )
            .ok()
        });
        let type_val = config.optional_str("/config/type").map(String::from);
        let labels = super::extract_labels(config);

        let mut model = google_cloud_security_privateca_v1::model::CertificateAuthority::default();
        model = model.set_name(provider_id);
        if let Some(v) = config_val {
            model = model.set_config(v);
        }
        if let Some(v) = gcs_bucket {
            model = model.set_gcs_bucket(v);
        }
        if let Some(v) = key_spec {
            model = model.set_key_spec(v);
        }
        if let Some(v) = lifetime {
            model = model.set_lifetime(v);
        }
        if let Some(v) = subordinate_config {
            model = model.set_subordinate_config(v);
        }
        if let Some(ref s) = type_val {
            model = model.set_type(
                google_cloud_security_privateca_v1::model::certificate_authority::Type::from(
                    s.as_str(),
                ),
            );
        }
        model = model.set_labels(labels);

        self.certificate_authority_service()
            .await?
            .update_certificate_authority()
            .set_certificate_authority(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .poller()
            .until_done()
            .await
            .map_err(|e| {
                super::classify_gcp_error("update_certificate_authority CertificateAuthority", e)
            })?;

        self.read_privateca_certificateauthority(provider_id).await
    }

    pub(super) async fn delete_privateca_certificateauthority(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.certificate_authority_service()
            .await?
            .delete_certificate_authority()
            .set_name(provider_id)
            .poller()
            .until_done()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteCertificateAuthority", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn privateca_capool_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn privateca_certificateauthority_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
