// Generated by smelt-codegen batch — do not edit by hand.
// Service: servicedirectory
// Resources: 2

use crate::provider::*;
use std::collections::HashMap;

use super::GcpProvider;

impl GcpProvider {
    pub(super) fn servicedirectory_namespace_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "servicedirectory.Namespace".into(),
            description: "Namespace resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![crate::provider::SectionSchema {
                    name: "identity".into(),
                    description: "Identity configuration".into(),
                    fields: vec![
                        crate::provider::FieldSchema {
                            name: "labels".into(),
                            description:
                                "Optional. Resource labels associated with this namespace.".into(),
                            field_type: crate::provider::FieldType::Record(vec![]),
                            required: false,
                            default: None,
                            sensitive: false,
                        },
                        crate::provider::FieldSchema {
                            name: "name".into(),
                            description:
                                "Immutable. The resource name for the namespace in the format"
                                    .into(),
                            field_type: crate::provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        },
                    ],
                }],
            },
        }
    }

    pub(super) async fn create_servicedirectory_namespace(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let _labels_val = config
            .pointer("/identity/labels")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();

        let labels = super::extract_labels(config);
        // Build SDK model
        let mut model = google_cloud_servicedirectory_v1::model::Namespace::default();
        model = model.set_name(name.clone());
        model = model.set_labels(labels);

        // Make API call
        let parent = format!("projects/{}/locations/{}", self.project_id, self.region);
        self.service_directory()
            .await?
            .create_namespace()
            .set_parent(&parent)
            .set_namespace_id(&name)
            .set_namespace(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_namespace Namespace", e))?;

        let provider_id = format!(
            "projects/{}/locations/{}/namespaces/{}",
            self.project_id, self.region, name
        );
        self.read_servicedirectory_namespace(&provider_id).await
    }

    pub(super) async fn read_servicedirectory_namespace(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let namespace = self
            .service_directory()
            .await?
            .get_namespace()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetNamespace", e))?;

        let user_labels: serde_json::Map<String, serde_json::Value> = namespace
            .labels
            .iter()
            .filter(|(k, _)| k.as_str() != "managed_by")
            .map(|(k, v)| (k.clone(), serde_json::json!(v)))
            .collect();

        let state = serde_json::json!({
            "identity": {
                "labels": user_labels,
                "name": namespace.name.as_str(),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&namespace.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_servicedirectory_namespace(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let labels = super::extract_labels(config);

        let mut model = google_cloud_servicedirectory_v1::model::Namespace::default();
        model = model.set_name(provider_id);
        model = model.set_labels(labels);

        self.service_directory()
            .await?
            .update_namespace()
            .set_namespace(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_namespace Namespace", e))?;

        self.read_servicedirectory_namespace(provider_id).await
    }

    pub(super) async fn delete_servicedirectory_namespace(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.service_directory()
            .await?
            .delete_namespace()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteNamespace", e))?;
        Ok(())
    }

    pub(super) fn servicedirectory_service_schema() -> crate::provider::ResourceTypeInfo {
        crate::provider::ResourceTypeInfo {
            type_path: "servicedirectory.Service".into(),
            description: "Service resource".into(),
            schema: crate::provider::ResourceSchema {
                sections: vec![
                    crate::provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "name".into(),
                                description: "Immutable. The resource name for the service in the format".into(),
                                field_type: crate::provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            crate::provider::FieldSchema {
                                name: "namespace_id".into(),
                                description: "Provider ID of the parent resource (injected via binding)".into(),
                                field_type: crate::provider::FieldType::Ref("*".into()),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    crate::provider::SectionSchema {
                        name: "config".into(),
                        description: "Config configuration".into(),
                        fields: vec![
                            crate::provider::FieldSchema {
                                name: "annotations".into(),
                                description: "Optional. Annotations for the service. This data can be consumed by service".into(),
                                field_type: crate::provider::FieldType::Record(vec![]),
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_servicedirectory_service(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());
        let name = config.require_str("/identity/name")?.to_string();

        // Build SDK model
        let mut model = google_cloud_servicedirectory_v1::model::Service::default();
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }
        model = model.set_name(name.clone());

        // Make API call
        let parent = config.require_str("/identity/namespace_id")?.to_string();
        self.service_directory()
            .await?
            .create_service()
            .set_parent(&parent)
            .set_service_id(&name)
            .set_service(model)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("Create_service Service", e))?;

        let provider_id = format!("{}/services/{}", parent, name);
        self.read_servicedirectory_service(&provider_id).await
    }

    pub(super) async fn read_servicedirectory_service(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        let service = self
            .service_directory()
            .await?
            .get_service()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("GetService", e))?;

        let state = serde_json::json!({
            "identity": {
                "name": service.name.as_str(),
            },
            "config": {
                "annotations": &service.annotations,
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert("name".into(), serde_json::json!(&service.name));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_servicedirectory_service(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        // Extract fields from config
        let annotations = config
            .pointer("/config/annotations")
            .and_then(|v| serde_json::from_value::<HashMap<String, String>>(v.clone()).ok());

        let mut model = google_cloud_servicedirectory_v1::model::Service::default();
        model = model.set_name(provider_id);
        if let Some(v) = annotations {
            model = model.set_annotations(v);
        }

        self.service_directory()
            .await?
            .update_service()
            .set_service(model)
            .set_update_mask(google_cloud_wkt::FieldMask::default())
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("update_service Service", e))?;

        self.read_servicedirectory_service(provider_id).await
    }

    pub(super) async fn delete_servicedirectory_service(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        let _name = provider_id
            .rsplit('/')
            .next()
            .unwrap_or(provider_id)
            .to_string();
        self.service_directory()
            .await?
            .delete_service()
            .set_name(provider_id)
            .send()
            .await
            .map_err(|e| super::classify_gcp_error("DeleteService", e))?;
        Ok(())
    }
}

// Diff: fields that force replacement
pub(super) fn servicedirectory_namespace_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}

// Diff: fields that force replacement
pub(super) fn servicedirectory_service_forces_replacement(path: &str) -> bool {
    matches!(path, "identity.name")
}
