// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: ecs
// Resources: 3

use smelt_provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn ecs_cluster_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "ecs.Cluster".into(),
            description: "Cluster resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![smelt_provider::SectionSchema {
                    name: "identity".into(),
                    description: "Identity configuration".into(),
                    fields: vec![smelt_provider::FieldSchema {
                        name: "name".into(),
                        description: "Cluster name".into(),
                        field_type: smelt_provider::FieldType::String,
                        required: true,
                        default: None,
                        sensitive: false,
                    }],
                }],
            },
        }
    }

    pub(super) async fn create_ecs_cluster(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let name = config.require_str("/identity/name")?.to_string();

        let tags = super::extract_tags(config);

        let mut req = self.ecs_client.create_cluster().cluster_name(&name);

        for (k, v) in &tags {
            req = req.tags(aws_sdk_ecs::types::Tag::builder().key(k).value(v).build());
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_cluster: {e}")))?;

        let container = result
            .cluster()
            .ok_or_else(|| ProviderError::ApiError("create_cluster returned no cluster".into()))?;
        let provider_id = container.cluster_arn().ok_or_else(|| {
            ProviderError::ApiError("create_cluster returned no cluster_arn".into())
        })?;

        self.read_ecs_cluster(provider_id).await
    }

    pub(super) async fn read_ecs_cluster(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .ecs_client
            .describe_clusters()
            .clusters(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_clusters: {e}")))?;

        let resource = result
            .clusters()
            .first()
            .ok_or_else(|| ProviderError::NotFound(format!("Cluster {provider_id}")))?;

        let state = serde_json::json!({
            "identity": {
                "name": resource.cluster_name().unwrap_or(""),
            },
        });

        let mut outputs = HashMap::new();
        outputs.insert(
            "cluster_arn".into(),
            serde_json::json!(resource.cluster_arn().unwrap_or("")),
        );
        outputs.insert(
            "cluster_name".into(),
            serde_json::json!(resource.cluster_name().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    #[allow(dead_code)]
    pub(super) async fn update_ecs_cluster(
        &self,
        _provider_id: &str,
        _config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        Err(ProviderError::RequiresReplacement(
            "resource does not support in-place update".into(),
        ))
    }

    pub(super) async fn delete_ecs_cluster(&self, provider_id: &str) -> Result<(), ProviderError> {
        self.ecs_client
            .delete_cluster()
            .cluster(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_cluster: {e}")))?;
        Ok(())
    }

    pub(super) fn ecs_service_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "ecs.Service".into(),
            description: "Service resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![smelt_provider::FieldSchema {
                            name: "name".into(),
                            description: "Service name".into(),
                            field_type: smelt_provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    smelt_provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "desired_count".into(),
                                description: "Number of tasks to run".into(),
                                field_type: smelt_provider::FieldType::Integer,
                                required: false,
                                default: Some(serde_json::json!(1)),
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "launch_type".into(),
                                description: "Launch type".into(),
                                field_type: smelt_provider::FieldType::String, /* Enum */
                                required: false,
                                default: Some(serde_json::json!("FARGATE")),
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "task_definition".into(),
                                description: "Task definition family or ARN".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_ecs_service(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let name = config
            .pointer("/identity/name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| ProviderError::InvalidConfig("identity.name is required".into()))?;

        let cluster_arn = config
            .get("cluster_arn")
            .or_else(|| config.pointer("/sizing/cluster_arn"))
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                ProviderError::InvalidConfig("cluster_arn is required for ECS Service".into())
            })?;

        let task_def = config
            .get("task_definition_arn")
            .or_else(|| config.pointer("/sizing/task_definition"))
            .and_then(|v| v.as_str())
            .ok_or_else(|| ProviderError::InvalidConfig("task_definition is required".into()))?;

        let desired_count = config
            .pointer("/sizing/desired_count")
            .and_then(|v| v.as_i64())
            .unwrap_or(1) as i32;

        let launch_type = config
            .pointer("/sizing/launch_type")
            .and_then(|v| v.as_str())
            .unwrap_or("FARGATE");

        let mut req = self
            .ecs_client
            .create_service()
            .cluster(cluster_arn)
            .service_name(name)
            .task_definition(task_def)
            .desired_count(desired_count)
            .launch_type(aws_sdk_ecs::types::LaunchType::from(launch_type));

        // Network configuration for Fargate
        if launch_type == "FARGATE" {
            let mut net_cfg = aws_sdk_ecs::types::AwsVpcConfiguration::builder();

            if let Some(subnets) = config
                .pointer("/network/subnet_ids")
                .and_then(|v| v.as_array())
            {
                for s in subnets {
                    if let Some(id) = s.as_str() {
                        net_cfg = net_cfg.subnets(id);
                    }
                }
            }
            if let Some(sid) = config.get("subnet_id").and_then(|v| v.as_str()) {
                net_cfg = net_cfg.subnets(sid);
            }
            if let Some(sgs) = config
                .pointer("/security/security_group_ids")
                .and_then(|v| v.as_array())
            {
                for sg in sgs {
                    if let Some(id) = sg.as_str() {
                        net_cfg = net_cfg.security_groups(id);
                    }
                }
            }
            if let Some(sg) = config.get("group_id").and_then(|v| v.as_str()) {
                net_cfg = net_cfg.security_groups(sg);
            }

            req = req.network_configuration(
                aws_sdk_ecs::types::NetworkConfiguration::builder()
                    .awsvpc_configuration(net_cfg.build().map_err(|e| {
                        ProviderError::InvalidConfig(format!(
                            "failed to build AwsVpcConfiguration: {e}"
                        ))
                    })?)
                    .build(),
            );
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("CreateService: {e}")))?;

        let service = result
            .service()
            .ok_or_else(|| ProviderError::ApiError("CreateService returned no service".into()))?;
        let arn = service
            .service_arn()
            .ok_or_else(|| ProviderError::ApiError("Service has no ARN".into()))?;

        let provider_id = arn;

        self.read_ecs_service(provider_id).await
    }

    pub(super) async fn read_ecs_service(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        // Parse cluster from ARN: arn:aws:ecs:region:acct:service/cluster/name
        let parts: Vec<&str> = provider_id.split('/').collect();
        let cluster = if parts.len() >= 2 { parts[1] } else { "" };

        let result = self
            .ecs_client
            .describe_services()
            .cluster(cluster)
            .services(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DescribeServices: {e}")))?;

        let service = result
            .services()
            .first()
            .ok_or_else(|| ProviderError::NotFound(format!("Service {provider_id}")))?;

        let state = serde_json::json!({
            "identity": { "name": service.service_name().unwrap_or("") },
            "sizing": {
                "desired_count": service.desired_count(),
                "running_count": service.running_count(),
                "task_definition": service.task_definition().unwrap_or(""),
                "launch_type": service.launch_type().map(|l| l.as_str()).unwrap_or(""),
            }
        });

        let mut outputs = HashMap::new();
        outputs.insert("service_arn".into(), serde_json::json!(provider_id));
        outputs.insert(
            "service_name".into(),
            serde_json::json!(service.service_name().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_ecs_service(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let parts: Vec<&str> = provider_id.split('/').collect();
        let cluster = if parts.len() >= 2 { parts[1] } else { "" };

        let mut req = self
            .ecs_client
            .update_service()
            .cluster(cluster)
            .service(provider_id);

        if let Some(td) = config
            .pointer("/sizing/task_definition")
            .and_then(|v| v.as_str())
        {
            req = req.task_definition(td);
        }
        if let Some(count) = config
            .pointer("/sizing/desired_count")
            .and_then(|v| v.as_i64())
        {
            req = req.desired_count(count as i32);
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("UpdateService: {e}")))?;

        self.read_ecs_service(provider_id).await
    }

    pub(super) async fn delete_ecs_service(&self, provider_id: &str) -> Result<(), ProviderError> {
        let parts: Vec<&str> = provider_id.split('/').collect();
        let cluster = if parts.len() >= 2 { parts[1] } else { "" };

        // Scale to 0 first
        let _ = self
            .ecs_client
            .update_service()
            .cluster(cluster)
            .service(provider_id)
            .desired_count(0)
            .send()
            .await;

        self.ecs_client
            .delete_service()
            .cluster(cluster)
            .service(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DeleteService: {e}")))?;
        Ok(())
    }

    pub(super) fn ecs_task_definition_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "ecs.TaskDefinition".into(),
            description: "TaskDefinition resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![smelt_provider::FieldSchema {
                            name: "name".into(),
                            description: "Task definition family name".into(),
                            field_type: smelt_provider::FieldType::String,
                            required: true,
                            default: None,
                            sensitive: false,
                        }],
                    },
                    smelt_provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "execution_role_arn".into(),
                                description: "Task execution IAM role ARN".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "task_role_arn".into(),
                                description: "Task IAM role ARN".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "sizing".into(),
                        description: "Sizing configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "containers".into(),
                                description: "Container definitions (name, image, port)".into(),
                                field_type: smelt_provider::FieldType::Record(vec![]),
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "cpu".into(),
                                description: "CPU units (256, 512, 1024, 2048, 4096)".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "memory".into(),
                                description: "Memory in MiB".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_ecs_task_definition(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let family = config
            .pointer("/identity/name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| ProviderError::InvalidConfig("identity.name is required".into()))?;

        let cpu = config
            .pointer("/sizing/cpu")
            .and_then(|v| v.as_str())
            .unwrap_or("256");
        let memory = config
            .pointer("/sizing/memory")
            .and_then(|v| v.as_str())
            .unwrap_or("512");

        let mut req = self
            .ecs_client
            .register_task_definition()
            .family(family)
            .cpu(cpu)
            .memory(memory)
            .network_mode(aws_sdk_ecs::types::NetworkMode::Awsvpc)
            .requires_compatibilities(aws_sdk_ecs::types::Compatibility::Fargate);

        // Execution role
        if let Some(role) = config
            .get("role_arn")
            .or_else(|| config.pointer("/security/execution_role_arn"))
            .and_then(|v| v.as_str())
        {
            req = req.execution_role_arn(role);
        }

        // Task role
        if let Some(role) = config
            .pointer("/security/task_role_arn")
            .and_then(|v| v.as_str())
        {
            req = req.task_role_arn(role);
        }

        // Container definitions
        if let Some(containers) = config
            .pointer("/sizing/containers")
            .and_then(|v| v.as_array())
        {
            for c in containers {
                let cname = c.get("name").and_then(|v| v.as_str()).unwrap_or("app");
                let image = c.get("image").and_then(|v| v.as_str()).unwrap_or("");
                let cport = c.get("port").and_then(|v| v.as_i64()).unwrap_or(0) as i32;

                let mut container = aws_sdk_ecs::types::ContainerDefinition::builder()
                    .name(cname)
                    .image(image)
                    .essential(true);

                if cport > 0 {
                    container = container.port_mappings(
                        aws_sdk_ecs::types::PortMapping::builder()
                            .container_port(cport)
                            .protocol(aws_sdk_ecs::types::TransportProtocol::Tcp)
                            .build(),
                    );
                }

                // Log configuration
                if let Some(lg) = c
                    .get("log_group")
                    .and_then(|v| v.as_str())
                    .or_else(|| config.get("log_group_name").and_then(|v| v.as_str()))
                {
                    container = container.log_configuration(
                        aws_sdk_ecs::types::LogConfiguration::builder()
                            .log_driver(aws_sdk_ecs::types::LogDriver::Awslogs)
                            .options("awslogs-group", lg)
                            .options("awslogs-region", "us-east-1") // TODO: from config
                            .options("awslogs-stream-prefix", cname)
                            .build()
                            .map_err(|e| {
                                ProviderError::InvalidConfig(format!(
                                    "failed to build LogConfiguration: {e}"
                                ))
                            })?,
                    );
                }

                req = req.container_definitions(container.build());
            }
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("RegisterTaskDefinition: {e}")))?;

        let td = result.task_definition().ok_or_else(|| {
            ProviderError::ApiError("RegisterTaskDefinition returned no def".into())
        })?;
        let arn = td
            .task_definition_arn()
            .ok_or_else(|| ProviderError::ApiError("TaskDefinition has no ARN".into()))?;

        let provider_id = arn;

        self.read_ecs_task_definition(provider_id).await
    }

    pub(super) async fn read_ecs_task_definition(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .ecs_client
            .describe_task_definition()
            .task_definition(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DescribeTaskDefinition: {e}")))?;

        let td = result
            .task_definition()
            .ok_or_else(|| ProviderError::NotFound(format!("TaskDefinition {provider_id}")))?;

        let containers: Vec<serde_json::Value> = td
            .container_definitions()
            .iter()
            .map(|c| {
                serde_json::json!({
                    "name": c.name().unwrap_or(""),
                    "image": c.image().unwrap_or(""),
                })
            })
            .collect();

        let state = serde_json::json!({
            "identity": { "name": td.family().unwrap_or("") },
            "sizing": {
                "cpu": td.cpu().unwrap_or(""),
                "memory": td.memory().unwrap_or(""),
                "containers": containers,
            }
        });

        let mut outputs = HashMap::new();
        outputs.insert("task_definition_arn".into(), serde_json::json!(provider_id));
        outputs.insert(
            "family".into(),
            serde_json::json!(td.family().unwrap_or("")),
        );
        outputs.insert("revision".into(), serde_json::json!(td.revision()));

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    #[allow(dead_code)]
    pub(super) async fn update_ecs_task_definition(
        &self,
        _provider_id: &str,
        _config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        Err(ProviderError::RequiresReplacement(
            "resource does not support in-place update".into(),
        ))
    }

    pub(super) async fn delete_ecs_task_definition(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.ecs_client
            .deregister_task_definition()
            .task_definition(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("DeregisterTaskDefinition: {e}")))?;
        Ok(())
    }
}
