// Generated by smelt-codegen batch (aws) — do not edit by hand.
// Service: secretsmanager
// Resources: 1

use smelt_provider::*;
use std::collections::HashMap;

use super::AwsProvider;

impl AwsProvider {
    pub(super) fn secretsmanager_secret_schema() -> smelt_provider::ResourceTypeInfo {
        smelt_provider::ResourceTypeInfo {
            type_path: "secretsmanager.Secret".into(),
            description: "Secret resource".into(),
            schema: smelt_provider::ResourceSchema {
                sections: vec![
                    smelt_provider::SectionSchema {
                        name: "identity".into(),
                        description: "Identity configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "description".into(),
                                description: "Secret description".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "name".into(),
                                description: "Secret name".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: true,
                                default: None,
                                sensitive: false,
                            },
                        ],
                    },
                    smelt_provider::SectionSchema {
                        name: "security".into(),
                        description: "Security configuration".into(),
                        fields: vec![
                            smelt_provider::FieldSchema {
                                name: "kms_key_id".into(),
                                description: "KMS key ID for encryption at rest".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: false,
                            },
                            smelt_provider::FieldSchema {
                                name: "secret_string".into(),
                                description: "Secret string value (sensitive)".into(),
                                field_type: smelt_provider::FieldType::String,
                                required: false,
                                default: None,
                                sensitive: true,
                            },
                        ],
                    },
                ],
            },
        }
    }

    pub(super) async fn create_secretsmanager_secret(
        &self,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        // Extract fields from config
        let description = config
            .optional_str("/identity/description")
            .map(String::from);
        let kms_key_id = config
            .optional_str("/security/kms_key_id")
            .map(String::from);
        let name = config.require_str("/identity/name")?.to_string();
        let secret_string = config
            .optional_str("/security/secret_string")
            .map(String::from);

        let tags = super::extract_tags(config);

        let mut req = self.secretsmanager_client.create_secret().name(&name);

        if let Some(ref v) = description {
            req = req.description(v);
        }
        if let Some(ref v) = kms_key_id {
            req = req.kms_key_id(v);
        }
        if let Some(ref v) = secret_string {
            req = req.secret_string(v);
        }
        for (k, v) in &tags {
            req = req.tags(
                aws_sdk_secretsmanager::types::Tag::builder()
                    .key(k)
                    .value(v)
                    .build(),
            );
        }

        let result = req
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("create_secret: {e}")))?;

        let provider_id = result
            .arn()
            .ok_or_else(|| ProviderError::ApiError("create_secret returned no arn".into()))?;

        self.read_secretsmanager_secret(provider_id).await
    }

    pub(super) async fn read_secretsmanager_secret(
        &self,
        provider_id: &str,
    ) -> Result<ResourceOutput, ProviderError> {
        let result = self
            .secretsmanager_client
            .describe_secret()
            .secret_id(provider_id)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("describe_secret: {e}")))?;

        let resource = &result;

        let mut state = serde_json::json!({
            "identity": {
                "name": resource.name().unwrap_or(""),
            },
        });
        if let Some(val) = resource.description().filter(|s| !s.is_empty()) {
            state["identity"]["description"] = serde_json::json!(val);
        }
        if let Some(val) = resource.kms_key_id().filter(|s| !s.is_empty()) {
            if state.get("security").is_none() {
                state["security"] = serde_json::json!({});
            }
            state["security"]["kms_key_id"] = serde_json::json!(val);
        }

        let mut outputs = HashMap::new();
        outputs.insert(
            "secret_arn".into(),
            serde_json::json!(result.arn().unwrap_or("")),
        );
        outputs.insert(
            "secret_name".into(),
            serde_json::json!(result.name().unwrap_or("")),
        );

        Ok(ResourceOutput {
            provider_id: provider_id.to_string(),
            state,
            outputs,
        })
    }

    pub(super) async fn update_secretsmanager_secret(
        &self,
        provider_id: &str,
        config: &serde_json::Value,
    ) -> Result<ResourceOutput, ProviderError> {
        let description = config.optional_str("/identity/description");
        let kms_key_id = config.optional_str("/security/kms_key_id");
        let secret_string = config.optional_str("/security/secret_string");

        let mut req = self
            .secretsmanager_client
            .update_secret()
            .secret_id(provider_id);

        if let Some(v) = description {
            req = req.description(v);
        }
        if let Some(v) = kms_key_id {
            req = req.kms_key_id(v);
        }
        if let Some(v) = secret_string {
            req = req.secret_string(v);
        }

        req.send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("update_secret: {e}")))?;

        self.read_secretsmanager_secret(provider_id).await
    }

    pub(super) async fn delete_secretsmanager_secret(
        &self,
        provider_id: &str,
    ) -> Result<(), ProviderError> {
        self.secretsmanager_client
            .delete_secret()
            .secret_id(provider_id)
            .recovery_window_in_days(30)
            .send()
            .await
            .map_err(|e| ProviderError::ApiError(format!("delete_secret: {e}")))?;
        Ok(())
    }
}
